### ISSUE TITLE
[Bug]: Can't Remove Copper Ingot from Ingot shelf

### ISSUE THREAD

**Issue by MrJohnnyB82** [FuryFight3r/ScrappingSimulator#10]
### Describe the bug

Place copper ingots on shelf, at one point I placed an Iron ingot on the shelf above, but it appeared on the shelf with the copper ingots.  I sold the iron ingot then placed more copper ingots on the shelf with the others.  notice it left a gap where the iron ingot had appeared.  Can only remove copper ingots up the the blank space where the iron ingot was.

### Reproduction Steps

1. placed iron ingots on top shelf
2. place copper ingots on middle shelf
3. place an iron ingot on top shelf it appeared on middle shelf
4. sold iron ingot
5. place copper ingots on middle shelf, left a gap where the iron ingot had appeared
6. remove copper ingots from middle shelf
7. cannot remove copper ingots before the gap the iron ingot made

### Expected behaviour

ingot to appear an the shelf in which they are place.  expect o be able to remove all ingots from the shelf

### Screenshot(s)/Video(s)

![20220123182808_1](https://user-images.githubusercontent.com/47801250/150702861-b0bb93bd-5055-4d01-98cc-7e4e6c4c1c0b.jpg)
![20220123182820_1](https://user-images.githubusercontent.com/47801250/150702864-20f17b57-4e60-459b-996a-c3e7579b1c35.jpg)

### Console output

NullReferenceException: Object reference not set to an instance of an object
PCInteract.Update () (at <058441ad052c421f9f988fc49220c056>:0)

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
queueingSystem.clickToCancel (System.Int32 id) (at <058441ad052c421f9f988fc49220c056>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <eaed1887017646508aa3fd7a8edf50d6>:0)
UnityEngine.Events.CachedInvokableCall`1[T].Invoke (System.Object[] args) (at <eaed1887017646508aa3fd7a8edf50d6>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <eaed1887017646508aa3fd7a8edf50d6>:0)
UnityEngine.UI.Button.Press () (at <978336161f1c4b6c97f9d637fd8dadda>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <978336161f1c4b6c97f9d637fd8dadda>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <978336161f1c4b6c97f9d637fd8dadda>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <978336161f1c4b6c97f9d637fd8dadda>:0)
UnityEngine.EventSystems.EventSystem:Update()

ERROR: A Pickup Object of the name Carry Box is stuck to the player! Now attempting to remove it.

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
queueingSystem.removeAllObjectsFromLists () (at <058441ad052c421f9f988fc49220c056>:0)
PCInteract.runCheck () (at <058441ad052c421f9f988fc49220c056>:0)
PCInteract.Update () (at <058441ad052c421f9f988fc49220c056>:0)

UnityException: Transform child out of bounds
ingotShelfStorage.returnLastIngot () (at <058441ad052c421f9f988fc49220c056>:0)
PCInteract.Update () (at <058441ad052c421f9f988fc49220c056>:0)

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7921708/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7921709/Player-prev.log)

**Comment by Poonfury** [comment]
Update.  Cant remove iron ingots from top shelf now.

UnityException: Transform child out of bounds
ingotShelfStorage.returnLastIngot () (at <058441ad052c421f9f988fc49220c056>:0)
PCInteract.Update () (at <058441ad052c421f9f988fc49220c056>:0)

**Comment by FuryFight3r** [comment]
Ahh I had thought I had fixed  this in the v0.28.3 update, I may need to restructure the Ingot Shelf Script and I will see if I can add a pass phrase that detaches all ingots and resets the count for the shelf as this seems to be the main problem, is that the counter seems to be skipping a number or Adds/Removes a number when it shouldn't be, then when it gets to the number that contains an empty slot it cannot find the information from the non existing Ingot, so hopefully I can make a work around for this, thanks again for the numours reports and helping make the game better :)

**Comment by Poonfury** [comment]
After save and reload I can remove copper and iron ingots.

**Comment by Poonfury** [comment]
I just found another, but I feel like I've hit you with enough over the last 24 hours. lol

**Comment by FuryFight3r** [comment]
Hehe, I don't mind, get these pesky bugs fixed :p

**Comment by FuryFight3r** [comment]
Hi there MrJohnnyB, I am very sorry for the delay on this patch, there were a lot more things wrong that I had first anticipated, nevertheless this issue should be fixed now, you will need to press [Right CTRL] + [F9] to open up the Command Panel, you can then type the 'reset_shelf' command to temporarily remove your shelf to recover the ingots, once the bugged Ingots have been recovered you can either retype the command or go to the Hardware Store and attempt to buy the shelf again so it can be turned back on (you wont need to pay for the shelf again). :)
