### ISSUE TITLE
[Bug]: <Sound levels>

### ISSUE THREAD

**Issue by OFSplays** [FuryFight3r/ScrappingSimulator#100]
### Describe the bug

If you leave the game and come back, the sound levels don't save.

**Comment by FuryFight3r** [comment]
Hi @OFSplays thank you for reporting this.
This should have been fixed in one of the v0.31 updates by removing the Main Menu Settings, though something else may be going wrong, I will look into this and hopefully have a fix in the next patch 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @OFSplays 
Thanks again for reporting this, this should now be solved in the [v0.33 Major Update](https://store.steampowered.com/news/app/1496640/view/3719455895098729681) :)
