### ISSUE TITLE
[Suggestion]: <faster trolley>

### ISSUE THREAD

**Issue by TranziT471** [FuryFight3r/ScrappingSimulator#102]
### What is your Suggestion?

trolley kinda doesnt make sense, being so slow  makes it kinda useless because you could just throw items away and repeat while using full sprint speed, being that you cant grab that many items in the trolley, makes it kinda useless if the speed was a bit faster it will make it useful and actually a time saving tool

### How will this suggestion fit into the Scope of Scrapping Simulator?

a better tool that makes more sense in the gameplay loop and becomes useful due to the economics of the game

### How would the Game and Community benefit from this suggestion?

.

**Comment by FuryFight3r** [comment]
Hi there @TranziT471,

I have already implemented a new system that handles the Trolley's speed in the coming v0.32.1 update 🎉 which is based off of the current weight of objects being carried, when empty, you will be able to move at 95% speed and as you add objects to the Trolley the speed starts declining, to a minimum of what the current speed is at the moment (around 40%) 👍

**Comment by FuryFight3r** [comment]
Hi there @TranziT471 and thanks again for your suggestion 🙂

I have since released the [v0.32.1 Update](https://store.steampowered.com/news/app/1496640/view/3730710456376651890?l=english) which adds a dynamic speed reduction to the Trolley 👍🙂
