### ISSUE TITLE
[Suggestion]: A Radio or CD Player for the garage

### ISSUE THREAD

**Issue by Paraglock** [FuryFight3r/ScrappingSimulator#103]
### What is your Suggestion?

Maybe add radio or CD player for the Garage. Radio can either be preloaded with copyright free music or the player can add their own music to an audio file. Either radio can be a find in the world, or purchased at the hardware store. Radio could also be recyclable.

### How will this suggestion fit into the Scope of Scrapping Simulator?

It was add an potential E-waste item and can give the player a little entertainment.

### How would the Game and Community benefit from this suggestion?

Players will be entertained and could potentially get more E-waste.

**Comment by FuryFight3r** [comment]
Hi there @Paraglock and thank you for your suggestion.
This has been suggested in the past and is planned to come in the near future 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @Paraglock 
Thanks again for the suggestion this has now been implemented in the [v0.33 Major Update](https://store.steampowered.com/news/app/1496640/view/3719455895098729681) :)
