### ISSUE TITLE
scrap yard owner

### ISSUE THREAD

**Issue by sdcole06** [FuryFight3r/ScrappingSimulator#108]
### Describe the bug

I am not sure if this is a bug or what but every day I owe money to the scrap yard owner like hundreds. if this is not a bug why am i owing him money? lol

**Comment by sdcole06** [comment]
I just tested it and in 1 day i owe him $441.00 I am just not sure why.

**Comment by FuryFight3r** [comment]
Hi the @sdcole06 and thank you for reporting this.

That is certainly not intended I will look into why this could be happening and have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @sdcole06 
Thanks again for Reporting this, this should now be resolved in the Late Updates :)
