### ISSUE TITLE
[Bug]: Floating bars under the carry box

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#110]
### Describe the bug

I put Copper and Gold bars in the carry box, saved the game and after reload the savegame, the bars are floating under the carry box. I'm not able to pick up the bars. They are stuck under the box. I have added a screenshot with this bars.

### Screenshot(s)/Video(s)

![Carrying_Box_Bug](https://user-images.githubusercontent.com/6820904/235212958-e8d716c7-5c6a-47ae-9592-52f86e477242.jpg)

### Console output

[28-04-2023--19-29-20.txt](https://github.com/FuryFight3r/ScrappingSimulator/files/11355980/28-04-2023--19-29-20.txt)

**Comment by FuryFight3r** [comment]
Hi there @senoks 
Thank you for reporting this, I am still trying to figure out what is causing this, though a quick fix is to remove and re-add the Ingots as it only seems to happen after loading into the game with the Ingots attached to the Carry Box, I will try have a patch for this with the next update 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @senoks 
Thanks again for reporting this, this has now been fixed in the [v0.33 Major Update](https://store.steampowered.com/news/app/1496640/view/3719455895098729681)
