### ISSUE TITLE
[Bug]: (visual) The 100g ingot mold is clipping into the table

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#112]
### Describe the bug

i'm not sure if it was always like this, but the ingot mold for gold and silver is now clipping into the table. you can notice this if you look into the casting part of it.

### Screenshot(s)/Video(s)

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/101810723/763584c8-c2f8-4c47-bffb-ff71ad069b31)

**Comment by FuryFight3r** [comment]
Thank you for reporting this, I think this may have been like this the whole time, as I haven't dabbled much with the Visual side of the Chem Set since it was introduced.
Nevertheless I will have this fixed up for the next update 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @aus2004, thanks again for reporting this, I have now released a small Hotfix that fixes this issue :)
