### ISSUE TITLE
[Bug]: (gameplay) The bug box on the chemistry table doesn't fit it properly

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#113]
### Describe the bug

there is a spot on the chemistry table where objects will be sent to the bug box even though you can just move objects there normally.

### Reproduction Steps

go to the chemistry table with any object
move the object between the legs where all the beakers are
it should go to the bug box.

**Comment by FuryFight3r** [comment]
That is odd, as I had removed (what I thought was) all the Bug Box colliders for the Ingot Shelf, Furnace Set and Chem Set since implementing the interfering object when purchasing feature.
I will look into this and remove any lingering colliders that are no longer needed 👍🙂

**Comment by FuryFight3r** [comment]
Hi again @aus2004, thanks again for reporting this, I have now released a small Hotfix that fixes this issue :)
