### ISSUE TITLE
[Bug]: Items get clipped though Pawn Shop doormat

### ISSUE THREAD

**Issue by BlueFoxSM** [FuryFight3r/ScrappingSimulator#117]
### Describe the bug

Depending on the item, it may get clipped through the blue and red doormats at the pawnshop entrance. 

### Reproduction Steps

Pick up a laptop or hard drive or thin item
Place it on the blue, or once doors open, the red doormat
It will then clip through. 
Here is a gif and a screenshot of both behaviors.
https://gyazo.com/5fc8182000dcac8f4544c5891eeff0e9
https://gyazo.com/082b0ecc7173b258f482017779cf6b48

### Expected behaviour

Item would rest on the doormat.

### Screenshot(s)/Video(s)

https://gyazo.com/082b0ecc7173b258f482017779cf6b48
https://gyazo.com/5fc8182000dcac8f4544c5891eeff0e9

### Console output

N/a / regular

### Player Logs

N/a

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
