### ISSUE TITLE
bug: scrapping simulator on steam

### ISSUE THREAD

**Issue by Diesel3879** [FuryFight3r/ScrappingSimulator#119]
### Describe the bug

when i up raw iron into the raw materials bucket it does not show up in the bucket when you look in the bucket it looks like it is empty but when you click on the bucket it shows the number amount of iron in the bucket and it reads full...

### Reproduction Steps

go into the game get 15000kg of raw iron and add all of it to the bucket and it should give the same outcome...

### Expected behaviour

be able to see the iron in the bucket...

**Comment by FuryFight3r** [comment]
Hi there @Diesel3879 and thank you for reporting this, this was a bug that arose when changing the new limit to 15kg, it for some reason made the visual side of things play up, this should however be fixed in the next update as the Bucket Scripts and Visuals have been reworked 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
