### ISSUE TITLE
bug-laptop

### ISSUE THREAD

**Issue by Diesel3879** [FuryFight3r/ScrappingSimulator#120]
### Describe the bug

disassembling the laptop on 6-11-2023 @ 13:58   got down to the motherboard after taking out the ram and everything else and it will not let me take out the motherboard it self.i tried the philips,flat and pliers and it will not let me take it apart the rest of the way.i play this the day before and i took the laptops apart with no issues.

### Expected behaviour

to be able to take the laptop apart all the way...

**Comment by FuryFight3r** [comment]
Hi there @Diesel3879 and thank you for reporting this, I have a suspicion that it may be related to the new E-Waste randomizer not properly setting the Laptops motherboard children to include the new RAM, I will investigate this and hopefully have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed as a Hotfix in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
