### ISSUE TITLE
[Bug]: Loading Savegame Issue

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#121]
### Describe the bug

After the latest upgrade v 0.33.1, there are not possible to load the save game. It "freezes" at 60% and nothing more can be done. 
I let it stay "loading" for 45 minutes and nothing happened. I uninstalled the game and reinstalled the game, but the savegame are still frozen at 60%.

Starting a new game are no problem, but only savegame are the problem.

### Screenshot(s)/Video(s)

![Scrapping_Bug_Load_Savegame](https://github.com/FuryFight3r/ScrappingSimulator/assets/6820904/6833d972-7de1-4fc7-84ae-10a3f2c6bee7)

**Comment by FuryFight3r** [comment]
Hi there @senoks and thank you for reporting this, some other players have also reported this via other sources, I am currently looking into the cause and hope to have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed as a Hotfix in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
