### ISSUE TITLE
[Bug]: Saving Stuck at 11%

### ISSUE THREAD

**Issue by Newsandbuy** [FuryFight3r/ScrappingSimulator#122]
### Describe the bug

After some time playing the auto and manual save get stuck at 11% "Saving: Partially Disassembled Objects", this can happen after 5 minutes or 2 hours. Forcing you to Alt F4 and lose everything up to your last save. I havent found a specific way to reproduce it, it seems to happen at random, i got it after fully disassembling things, partially, refining gold etc.

### Reproduction Steps

1. Start the game and load a save.
2. Play, Disassemble things, melt bars etc.
3. Save.

### Expected behaviour

Game Saves and you can continue to play.

### Console output

NullReferenceException
referenceManager.determineIdObjects () (at <5065b330e68e4b8ca3479a1d09044693>:0)
saveLoadManager+<savingProcess>d__24.MoveNext () (at <5065b330e68e4b8ca3479a1d09044693>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c6a0be87269c4a56aa4c8bc00101797f>:0)

**Comment by FuryFight3r** [comment]
Hi there @Newsandbuy and thank you for reporting this, there has been some strange things happening lately.
If at all possible, are you able to send me your save file? That way I can load up your save which should aid me in finding the error 🙂👍

**Comment by Newsandbuy** [comment]
sure, ziped it up since GitHub doesnt support .es3

[Scrapping_Simulator_Data.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/11854195/Scrapping_Simulator_Data.zip)

**Comment by FuryFight3r** [comment]
> sure, ziped it up since GitHub doesnt support .es3
> 
> [Scrapping_Simulator_Data.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/11854195/Scrapping_Simulator_Data.zip)

Great thank you very much for that :)

I have just released the [v0.33.2 Hot Fix](https://store.steampowered.com/news/app/1496640/view/3648526737380492526)  which should hopefully solve this issue, I wasn't able to Replicate the issue though I did find some questionable parts within the Script that produced the error you had posted so fingers crossed it shouldn't happen any longer :)
