### ISSUE TITLE
[Bug]: Removable SSD Cover

### ISSUE THREAD

**Issue by Newsandbuy** [FuryFight3r/ScrappingSimulator#123]
### Describe the bug

You are able to remove the SSD top cover by clicking on it without removing the screws.

### Reproduction Steps

1. Place any SSD on the bench
2. Enter Disassembly mode
3. Click on the top cover

### Expected behaviour

Needing to remove the 4 screws before you can open the top cover.

### Console output

No Warning/Error

**Comment by FuryFight3r** [comment]
Hi there @Newsandbuy and thank you for reporting this, I will have this fixed asap 👍🙂

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, I have just pushed a hotfix to the v0.33.2 Update to fix this issue :)
