### ISSUE TITLE
[Suggestion]: Weather and Stainless Steel

### ISSUE THREAD

**Issue by gold500006** [FuryFight3r/ScrappingSimulator#126]
### What is your Suggestion?

can we have weather in the game like snow thunder lighing rain fog and can we all so have stanless steel scrap in the game and scraping cars as well for scrap it would make the game more intresing 

### How will this suggestion fit into the Scope of Scrapping Simulator?

it would make the game more intresting 

### How would the Game and Community benefit from this suggestion?

i think people would love that

**Comment by FuryFight3r** [comment]
Hi there @gold500006 and thank you for your suggestions 🙂

Weather and Time of Day has been in the game for around 12 months or so now, however Snow and Snow Storms are not implemented to resemble a more Australian like environment, which does include Rain and Thunderstorms however they are not as common as a hot day, this also depends on your current time of year in-game which also effects weather probabilities, starting off in January you will begin in Summer which means a lot of sunny days and little Rain, as you progress through the months it becomes colder and more likely to rain/thunderstorm. (Think of Aus as the Opposite of the US/UK, we have Scorching Hot Christmas and Freezing Cold/Wet/Miserable mid year) 😅

I am a little hesitant on adding more materials as it would begin going down a rabbit hole of having to add many other materials from, tantalum, titanium, cobalt, platinum, lead, steel, stainless steel, zinc, palladium, etc, etc, and not only just adding those materials, but also creating viable reasons for them to exist in the game, while also creating means of gaining/storing/refining/selling etc, so limiting the materials to more base metals that are more relatable and recognizable I feel is the easiest solution to getting the game released asap and wouldn't over complicate both the UI and game while still portraying the desired message.

That way I feel I can finish up the game in a timely manner as I don't really want to be still working on this game for another handful of years, as it has already been in development for nearly 4 years (1 year outside Steam, and 2 1/2 years on steam early access) so I am at that stage now where I just want to get it to 1.0 release asap and move on to the next project as I feel I have began losing grasp of the end goal and am now just stuck in a loop of adding more content to keep players entertained.

Nevertheless development progress has really started picking up again lately after getting through some tough bugs/issues and I hope to have the game in Beta v0.5 (Open World Map, Cars, Tasks/Quests, New E-Waste etc) by the end of this year which should pave the way for the 1.0 release 🙂

I apologise for the lengthy comment, I tend to go off on a tangent 😅😅

You can also check the road map, which will give you an outline on what is to come 🙂👍

[Road Map 2023](https://github.com/FuryFight3r/ScrappingSimulator/wiki/Scrapping-Simulator-Road-Map-2023)
