### ISSUE TITLE
[Bug]: Lost Ingot Box

### ISSUE THREAD

**Issue by gold500006** [FuryFight3r/ScrappingSimulator#127]
### Describe the bug

i went to the scrap yard with 12 iron ingots in the wooden box i put wooden box on floor and box went throw the floor with 12 ingots i lost it i look in the box in my house its not there i have loads of ingots i cant move them to sell now with out that box the game wont let me buy another box so explain what am i going to do now with no ingot box 

### Expected behaviour

i thouht i get the box back i didnt

**Comment by FuryFight3r** [comment]
Pressing F1 will bring up the Command Panel which give you the ability to fix most known issues, by typing 'reset_ingot_box' or it may be 'return_ingot_box' will return the carry box to the Lost & Found Box inside your house

**Comment by gold500006** [comment]
ok thank you

**Comment by FuryFight3r** [comment]
You're welcome 🙂👍
