### ISSUE TITLE
[Bug]: Items not properly clearing from worktable after dissasembly

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#129]
### Describe the bug

After disassembling a DVD player the table was blocked with an invisible "DVD Player" that could possibly be picked up. I managed to remove it and then disassemble the CD drive and the same thing occurred. 

This prevents the player from adding new items to the table and is probably leaving invisible components in the garage.

This occurred after purchasing and filling the new safe under the table. It was not a problem when I ran the new tutorial disassembly.

### Reproduction Steps

1. Purchase a safe upgrade and add some items to both shelves
2. Go to the garage
3. Dissasemble an item
4. Attempt to add a new item to the table.

**Comment by FuryFight3r** [comment]
Hi there @JackDaring and thank you for reporting this.
I will have to do some more investigation with this, as that seems very odd that it only happens after buying the vault, as the vault is an entirely unrelated system to the desk, disassembly and items so it would be very odd that purchasing the vault alters the way items are disassembled.

Nevertheless I will look into this 🙂👍

**Comment by XenoJiiva0053** [comment]
this happeneds to me too. but i have no upgrades at all. so far its happened with both microwave. server and power supply unit

**Comment by FuryFight3r** [comment]
Hi there @JackDaring and @XenoJiiva0053 and thank you for reporting and confirming this bug, I have just pushed a Hot Fix to patch this issue 🙂
Any lingering invisible items on your save will be removed upon loading into this revised v0.34 version 🙂👍
