### ISSUE TITLE
[Bug]: Time Frozen

### ISSUE THREAD

**Issue by gold500006** [FuryFight3r/ScrappingSimulator#130]
### Describe the bug

im playing the game and its night time and the time is stuck at 10;09 am the pawn shop the hardwere shop and the scrapyard opens at 8am there are still shut 

### Expected behaviour

i expect that i cant play the game

**Comment by FuryFight3r** [comment]
Hi there @gold500006, I do apologise for the Bugs in the latest update and thank you for reporting this.
The issue happening here is somehow the Time UI Script and become unlinked from the World Time, but am currently a little uncertain as to why this could be happening 🤔

You may be able to type the 'fix_time' command by pressing [F1], to sync the system back up, though this may cause you to pass out if the current world time exceeds 12am midnight and is less than 5am

Nevertheless I will look into what could be causing this and hopefully have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @gold500006 and thank you for reporting this, this should now be fixed in the [v0.35.2 Update](https://store.steampowered.com/news/app/1496640/view/3746489543130817906) 🙂👍
