### ISSUE TITLE
Invisible objects

### ISSUE THREAD

**Issue by CNoteGaming** [FuryFight3r/ScrappingSimulator#132]
### Describe the bug

After completing the tutorial I placed a DVD player on my disassembly table and once the disassembly was complete it left the object invisible on the table.

**Comment by FuryFight3r** [comment]
Hi there @CNoteGaming, thank you for reporting this, other users have reported the same bug, but unfortunately in many, many hours of bug and stress testing this latest build, sadly I haven't yet been able to replicate any of these bugs.

If you are able to provide more information about the issue it will hopefully help me in tracking down and fixing the bug.

By pressing [F5] will bring up the Debug Log which provides some brief logs about what is happening behind the scenes, this will also generally print Red Errors when something breaks, if you could copy/paste or screenshot any and all red errors that should hopefully help me in finding the source of the issue 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @CNoteGaming, thanks again for reporting this, I was finally able to replicate this bug and have just pushed a Hot Fix to patch the issue, upon loading your game save on this revised v0.34 version any lingering Invisible Items will be removed from your game :)
