### ISSUE TITLE
Screen turns solid color if you are zoomed in

### ISSUE THREAD

**Issue by Paraglock** [FuryFight3r/ScrappingSimulator#133]
### Describe the bug

If you have zoomed into a part(RMB) before you start to dissemble it, after you have completed the teardown, the screen will become the solid color of the next part that needs to be dissemble.

### Reproduction Steps

1.)Put a part to be dissembled on the workbench
2.)Zoom in on the part(RMB)
3.)Press E to start dissembling
4.)Dissemble part and finish
5.)Watch as screen fills with color of the next part to be dissembled(Circurt board with be green, DVD will be grey, etc.)

### Expected behaviour

After dissembling, the camera should zoom out.

### Console output

Screen position out of view frustum (screen pos 639.000000, 360.000000) (Camera rect 0 0 1280 720)

### Player Logs

[Scrapping_Simulator_Data.es3.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/12291993/Scrapping_Simulator_Data.es3.zip)

**Comment by FuryFight3r** [comment]
Hi there @Paraglock and thank you for reporting this, I will see about having this patched in the next update 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @Paraglock, Thanks again for reporting this, this should now be fixed in the [v0.35 Major Update](https://store.steampowered.com/news/app/1496640/view/3686814404776291600) 👍
