### ISSUE TITLE
[Suggestion]: Increase LOD and draw distances

### ISSUE THREAD

**Issue by TwinMinds** [FuryFight3r/ScrappingSimulator#134]
### What is your Suggestion?

Please expand draw distance and LOD distances, especially on ultra quality preset.  Currently the LOD and draw distances are very short, causing a lot of visual pop-in effect that is very noticeable.

In these screenshots, you can see the different LOD models for the fence, one is solid white and the other has visual fence boards.  These pop in a line you approach the fence at a very short distance, which is shortly after the fence popped into existence only moments earlier less than half a city block away.

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/64905062/2eeb8b58-6822-47b6-8606-89d92faee663)

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/64905062/47e6346d-8b93-4fed-8af5-bac49c6d218d)

### How will this suggestion fit into the Scope of Scrapping Simulator?

It would make the game more visually consistent and appealing.

### How would the Game and Community benefit from this suggestion?

Same as above, visual consistency and appeal.

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds and thank you for reporting this, I can certainly see about tweaking the Environment LODs for better visuals 🙂👍
You can however toggle the 'Custom' quality setting (Below Ultra) which gives you additional tweakable setting including an 'Insane' LOD distance setting below the 'Ultra' Quality Preset which is basically a realism setting that I primarily use for Screenshots and Media, this setting will allow you to see very far at full detail, though be wary it can cause quite a bit of system strain

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds and thank you again for this suggestion, This has now been improved in the [v0.35.2 Update](https://store.steampowered.com/news/app/1496640/view/3746489543130817906?l=english) 🙂👍
