### ISSUE TITLE
[Bug]: Description for Raw Material Storage Bucket is incorrect

### ISSUE THREAD

**Issue by TwinMinds** [FuryFight3r/ScrappingSimulator#135]
### Describe the bug

In the hardware store, the description for the materials bucket states it holds 30,000g (30kg).  When actually using the bucket, it only holds 15kg of material.

### Reproduction Steps

1. Visit the hardware store
2. Mouse over the Raw Material Storage Bucket, take note of 30kg storage listing
3. Buy storage bucket
4. Mouse over Storage Bucket, take note of 15kg actual capacity

### Expected behaviour

Expected behavior is consistent tooltip information that accurately describes item usability.

### Screenshot(s)/Video(s)

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/64905062/22553784-ded0-448e-bef5-343d501c540c)

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/64905062/1a7bfdbb-1d0e-4c4b-9a0d-70236f6cac67)

### Console output

No errors present

### Player Logs

No errors present

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds thank you for reporting this, I had meant to change that many updates ago when the buckets changed from 30 to 15kg, I will remember to fix it for the next patch 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds 

Thank you for reporting this, this issue should now be fixed in the [v0.35.1 Update](https://store.steampowered.com/news/app/1496640/view/3713837177194719695?l=english) 🙂👍
