### ISSUE TITLE
[Bug]: Processing Silver shows Gold in the beaker after step 2

### ISSUE THREAD

**Issue by TwinMinds** [FuryFight3r/ScrappingSimulator#136]
### Describe the bug

After completing step 2 of the beaker process attempting to process 120g of silver, the resulting beaker mouse-over text shows "This solution contains gold and waste chemicals" instead of Silver.  After disposing of waste chemicals, it now says it contains 99% silver and drying.

### Reproduction Steps

1. Finish step 1 and 2 of processing silver in the beaker
2. Prior to emptying waste chemicals, read mouse-over text indicating gold is in the beaker
3. Profit?

### Expected behaviour

Beaker contents should consistently list Silver when processing Silver.

### Player Logs

There were no errors in the console, it only stated "Completed step 2 of beaker process"

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds and thank you for reporting this, I should have it fixed asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @TwinMinds

Thank you for reporting this, this issue should now be fixed in the [v0.35.1 Update](https://store.steampowered.com/news/app/1496640/view/3713837177194719695?l=english) 🙂👍
