### ISSUE TITLE
[Bug]: 8GB DDR4 Laptop RAM stick says DDR3 after you pick it up

### ISSUE THREAD

**Issue by the1within0** [FuryFight3r/ScrappingSimulator#137]
### Describe the bug

This appears to be a text error. The components of the RAM are indeed different, it just says DDR3 instead of DDR4

Item | Waste | Iron | Aluminum | Copper | Silver | Gold
-- | -- | -- | -- | -- | -- | --
8GB DDR3 Laptop RAM Stick|74.10|6.09|7.56|40.43|1.89|2.52
8GB DDR4 Laptop RAM Stick|68.40|7.35|8.82|46.73|2.52|3.15

### Reproduction Steps

1. Find a laptop with 8GB DDR4 Laptop RAM in it
2. Remove the RAM
3. Look in the Parts bin and it says "8GB DDR3 Laptop RAM Stick" now.

### Expected behaviour

The text should still read "8GB DDR4 Laptop RAM Stick"

Also, the 8GB sticks have 12 x 512MB chips, which is only 6GB, and I would expect the numbers to add up to 8GB

### Screenshot(s)/Video(s)

![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/145245119/5a5d4f80-ecbc-40ae-ad74-2db980448431)
![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/145245119/d43b0217-50c2-4a36-8b24-fa9353b0a869)

### Console output

8gbddr3_L(Clone) Is checked as 'hasDeconAnim', but a Animator Component was not found!
8gbddr4_L(Clone) Is checked as 'hasDeconAnim', but a Animator Component was not found!

**Comment by FuryFight3r** [comment]
Hi there @the1within0 and thank you for reporting this issue, I will have this patched asap 🙂👍

**Comment by the1within0** [comment]
Another case:
![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/145245119/69dde46c-4b25-4b45-940c-3b3417af7304)
becomes
![image](https://github.com/FuryFight3r/ScrappingSimulator/assets/145245119/c4ad3822-884f-4439-b0c4-5eda29124b86)

**Comment by FuryFight3r** [comment]
Hi there @the1within0, and thank you for the update, yeah something is certainly wrong there, I believe v0.34 I had done a bit of reworking to the Sub E-Waste spawning system, and it seems like the ID being provided when the item is being removed is 1 less than the actual ID of the specific RAM, thus causing it to spawn the lesser/smaller RAM below the removed one, hopefully can have this patched asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @the1within0 

Thank you for reporting this, this issue should now be fixed in the [v0.35.1 Update](https://store.steampowered.com/news/app/1496640/view/3713837177194719695?l=english) 🙂👍
