### ISSUE TITLE
[Bug]: Buckets will convert any material to any other material

### ISSUE THREAD

**Issue by the1within0** [FuryFight3r/ScrappingSimulator#138]
### Describe the bug

I accidentally change the material type of a bucket with iron in it to alum

### Reproduction Steps

1. Set the material type for a bucket (e.g. Waste)
2. Add all the waste you want to the bucket (e.g. 15 kg)
3. Select the material type, and choose a different material (e.g. Gold)
4. Remove all the other material you want (e.g. turn 15 kg of waste into gold)

Note: You can't close the UI between steps 3 and 4

### Expected behaviour

You should not be able to convert the material of the contents of the bucket.

### Console output

Nothing is logged

**Comment by FuryFight3r** [comment]
Hi there @the1within0, thank you for reporting this, that is quite odd as the materials selection should restrict a change of any amount of a material is contained, I will look into this and try replicate it to fix and patch 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @the1within0 

Thank you for reporting this, this issue should now be fixed in the [v0.35.1 Update](https://store.steampowered.com/news/app/1496640/view/3713837177194719695?l=english) 🙂👍
