### ISSUE TITLE
[Bug]: Saving Failed on "Saving: Mine Sweepin Best Score"

### ISSUE THREAD

**Issue by BigMacSauce** [FuryFight3r/ScrappingSimulator#139]
### Describe the bug

I had begun to notice after gaining the achievement for Mine Sweepin that anytime I saved, the portion relating to the best score for Mine Sweeping takes longer and longer. On the last success, it took over 5 minutes. This save, I have been leaving it running for 10+ minutes and still says 100% but refuses to move forward. I do have an excessive amount of objects within the save (I would estimate 400 or so, I can't just leave good scrap to go to waste!). But it is specifically failing on the Mine Sweepin Part it appears. Planning to sleep as soon as I finish this report, will just sorta... leave it running to see what happens. I would rather not lose the save as I have like 14 hours on it. It is also an old save (July of 2022, managed to keep it alive this long). Will add save log and such after I wake, as I want to see what happens when I leave it first 

![image_2023-09-17_045018110](https://github.com/FuryFight3r/ScrappingSimulator/assets/9386936/29f79456-bb48-4dfe-80c7-23078d8a8c4b)

**Comment by FuryFight3r** [comment]
Hi there @BigMacSauce, thank you for reporting this, that is quite odd indeed, I will certainly look into this and have it patched asap 🙂👍

**Comment by BigMacSauce** [comment]
Just an update. After leaving it overnight it did at somepoint swap over to a "Saving: Completed" screen. Unsure of when, as I was asleep, but I would say it was on the Mine Sweepin screen for 30+ minutes. It never actually returned me to game however, so I did a good ol' Alt+F4, and then reloaded the game. Loaded the save, and it actually does appear to have properly saved. Also it seems to save properly now, as I did a save and it only took about 5 seconds.

Attached log for you. If you want more data, please let me know! Love the game, and happy to help however I can. 

[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/12643467/Player-prev.log)

**Comment by FuryFight3r** [comment]
Hi there @BigMacSauce and thank you for the Update, it is certainly a strange bug and something I haven't yet encountered yet, but will look into it and see what could be causing it 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @BigMacSauce and thank you again for reporting this, this should now be fixed in the (v0.35.2 Update)[https://store.steampowered.com/news/app/1496640/view/3746489543130817906] 🙂👍
