### ISSUE TITLE
[Suggestion]: Solar/wind power

### ISSUE THREAD

**Issue by the1within0** [FuryFight3r/ScrappingSimulator#144]
### What is your Suggestion?

House upgrade to get a solar panel (that won't work at night or in clouds) or wind generator (that won't work with no wind/too much wind)

### How will this suggestion fit into the Scope of Scrapping Simulator?

It's a very green solution to getting power, as we find more uses for power other than lighting or crypto mining

### How would the Game and Community benefit from this suggestion?

We can purchase a house upgrade to start selling power back to the grid and not having to pay that power bill

**Comment by FuryFight3r** [comment]
Hi there @the1within0
I can certainly see about adding this, I had attempted this very near to the Early Access release, but ran into a handful of issues and never went back to it 😅 I am sure I could implement a greener form of energy  to help save on power costs 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @the1within0 

Thank you again for suggesting this, this has now been implemented in the [v0.36 Major Update](https://store.steampowered.com/news/app/1496640/view/3975056740187061180) 👍
