### ISSUE TITLE
Can’t take Motherboard out of Laptops

### ISSUE THREAD

**Issue by Paraglock** [FuryFight3r/ScrappingSimulator#146]
### Describe the bug

When trying to remove the motherboard out of a laptop, a message appears like there is something blocking it from being removed , even though nothing is blocking it.

### Reproduction Steps

1.)Obtain a laptop
2.)Put Laptop on desk and start to take apart until you get to the motherboard.
3.)Try to take motherboard out and fail
4.)Weep with frustration.

### Expected behaviour

Mother board should come out

### Screenshot(s)/Video(s)

Check out my video to see the bug

**Comment by Deluthe** [comment]
I've also run into this issue when playing the game as well

**Comment by FuryFight3r** [comment]
Hi there @Paraglock and @Deluthe, thank you for reporting this, I have discovered this was due to the RAM Slots staying active and causing the Child objects detect error, I hope to have this patch released asap :)

**Comment by FuryFight3r** [comment]
Thank you for reporting this, this has now been patched in the [v0.35.2 Update](https://store.steampowered.com/news/app/1496640/view/3746489543130817906?l=english) 🙂👍
