### ISSUE TITLE
[Bug]: Unable to see active deliveries on PC after patch update

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#15]
### Describe the bug

This is probably due to the update but I had a number of deliveries that were in transit I guess when I updated the save.

The system recognizes them and sends me notifications that they are ready to collect but the deliveries list is blank on the PC.  

The scrolling slider also appears to be present on the deliveries page suggesting the items are listed there.

New accepted email deliveries work despite this.

### Reproduction Steps

1. Have 10 active deliveries from the previous save
2. update the game to the latest version.
3. PC no longer displays the active deliveries though the system will alert you when they have arrived,

### Expected behaviour

PC should show the active deliveries or there should be a way to clear them from the PC.

**Comment by FuryFight3r** [comment]
Hi there JackDaring,
That is really strange, was there any error print outs either when loading your save or when the invisible deliveries finish? As by the sounds of it they may still be active somewhere in the world, but may not be attached to the PC for some reason (this is just my best guess).

I may need you to send your Save File if at all possible as this may be quite difficult to replicate and track down how it happened.

Thank you for reporting this :)

**Comment by FuryFight3r** [comment]
Added patch for this issue into v0.28.4 - Thank you for reporting this :)
