### ISSUE TITLE
The purchased buckets have disappeared.

### ISSUE THREAD

**Issue by Robo699** [FuryFight3r/ScrappingSimulator#151]
### Describe the bug

The purchased buckets have disappeared. I bought 4 buckets and took 2 home on my trolley, when I returned to get the other 2, the hardware store had already closed. The morning after they opened, they were no longer there, however, when I purchased new ones, it says that I still own 4.

### Expected behaviour

If you buy things in a store and leave them there overnight, they should at least show up for pickup outside the store.

**Comment by FuryFight3r** [comment]
Hi there @Robo699 
Thank you for reporting this 👍

So I can investigate this issue further, would it be possible for you to send through your save file? You can send it in here, our Discord server via DM or via email admin@defectgaming.com

This will greatly help me in understanding what has gone wrong and how I could go about fixing it effectively.
