### ISSUE TITLE
[Bug]: Gold/Silver bars Stuck in hand and multiplying

### ISSUE THREAD

**Issue by Newsandbuy** [FuryFight3r/ScrappingSimulator#153]
### Describe the bug

Whenever u pick up a gold/silver bar it gets stuck in my hand, i cant drop it unless i restart the game, if i try to place it in the safe, an ingot gets added but its still in my hand, so i can add infinite bars to the safe.

### Reproduction Steps

1. Pickup gold/silver bar
2. place it in the safe, 

repeat step 2.

### Expected behaviour

letting go of LMB should drop the bar and you should only add the current bar to the safe

### Console output

NullReferenceException: Object reference not set to an instance of an object
Pickup.distToVault () (at <c43317de41fc4a0cb3a943823d058a23>:0)
Pickup.Update () (at <c43317de41fc4a0cb3a943823d058a23>:0)

### Player Logs

[Scrapping Simulator.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/14616923/Scrapping.Simulator.zip)

**Comment by FuryFight3r** [comment]
Hi there @Newsandbuy
Thank you for reporting this, I will look into this first thing and have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Thank you again for reporting this, I have just pushed a hotfix that will fix this issue :)
