### ISSUE TITLE
[Suggestion]: Tone down bloom and bloom settings

### ISSUE THREAD

**Issue by Tiberius-Ryx-Tyr** [FuryFight3r/ScrappingSimulator#155]
### What is your Suggestion?

Perhaps Turning down the bloom a little ~~or adding a bloom setting would be nice~~. Everything looks blurry as a result.

### How will this suggestion fit into the Scope of Scrapping Simulator?

Be more enjoyable for some people who dislike over the top bloom.

### How would the Game and Community benefit from this suggestion?

Add more options for people to customize the way the game looks that suits them.

**Comment by Tiberius-Ryx-Tyr** [comment]
So I just saw the next page prompt on the custom graphics settings and there is a bloom toggle, I think bloom overall needs to be toned down a bit.

**Comment by FuryFight3r** [comment]
Hi there @Tiberius-Ryx-Tyr 
Thank you for reporting this, a lot of visual settings had been adjusted heavily in the last (v0.37) update when attempting to rectify weather/time of day issues, which as a result has left some things looking a little out of place, the next update should improve the overall look 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @Tiberius-Ryx-Tyr,
I have just released a Hotfix that reduces the intensity of the bloom effect by a factor of half, which should make it a bit less glaring, thank you again for your suggestion :)
