### ISSUE TITLE
[Bug]: Ingot Rack Disapears

### ISSUE THREAD

**Issue by Tiberius-Ryx-Tyr** [FuryFight3r/ScrappingSimulator#156]
### Describe the bug

I don't know when but my Ingot rack disappeared, and it reappeared when I bought a Ingot mold in the shop, must have refreshed something. I checked the store and it said I had the rack, tried buying it again

### Reproduction Steps

Unknown. Maybe it was caused by my Ingot carry box being too close to the rack I don't know

### Expected behaviour

To not disappear randomly

### Screenshot(s)/Video(s)

![20240328163359_1](https://github.com/FuryFight3r/ScrappingSimulator/assets/165326221/e945de96-58ba-46e3-8437-3fb3a312e290)

### Console output

Unknown

### Player Logs

Unknown

**Comment by FuryFight3r** [comment]
Hi there @Tiberius-Ryx-Tyr 
Thank you for reporting this, that is quite an odd one, I don't imagine it would have anything to do with the Ingot Box positioning, nevertheless I will look into this 🙂👍

**Comment by Tiberius-Ryx-Tyr** [comment]
Oh, Save and Reload didn't manage to make it re-appear at all

**Comment by FuryFight3r** [comment]
That is quite odd, as reloading should certainly correct most issues as per the way I have setup the buyable objects 🤔

I may need a bit more info on this to help me in diagnosing the issue at hand, when in-game you can press [F8] to create a partial in-game Bug Report, following the steps will Pack your Save File and Player Logs for me to look into and aid with testing/fixing, it will create a secondary Bug Report on GitHub, but that's fine I may be able to merge it into this report if possible 👍

**Comment by Tiberius-Ryx-Tyr** [comment]
I'll keep that in mind for next time

**Comment by FuryFight3r** [comment]
That's fine, though I may still need the Log/Save files to fix this specific issue if you wanted the issue fixed, but if the issue is already resolved itself or you'd prefer to start a new game to fix the issue then there would be no need to send the files 👍🙂

**Comment by Tiberius-Ryx-Tyr** [comment]
Where are the In-game generated reports located?

**Comment by FuryFight3r** [comment]
When you click the 'Generate Zip File' button within the In-Game bug report feature it should automatically open the directory for you, it should be the only Zip file there 🙂👍

**Comment by Tiberius-Ryx-Tyr** [comment]
Oh It seems to happen whenever I have the Ingot Carry box right next to it Save and Restart. I think its the Hide_Shelf command getting set to true on game start, I can get it to re-appear by setting it to false.

**Comment by Tiberius-Ryx-Tyr** [comment]
> When you click the 'Generate Zip File' button within the In-Game bug report feature it should automatically open the directory for you, it should be the only Zip file there 🙂👍

Huh it doesn't open anything for me.

**Comment by Tiberius-Ryx-Tyr** [comment]
![20240328193130_1](https://github.com/FuryFight3r/ScrappingSimulator/assets/165326221/4a628fa5-4903-42a1-af47-2503cdbc9532)
![20240328193218_1](https://github.com/FuryFight3r/ScrappingSimulator/assets/165326221/fc5f2c5c-7b62-4aed-853d-e6dc48565120)

**Comment by FuryFight3r** [comment]
That's incredibly strange, as the only possible way to turn the shelf off is by the user manually typing the 'hide_shelf=true' command or the only other possible reason the shelf won't turn back on when loading is if it thinks you don't own it, which leads me to believe it's a save file issue. At this stage there is no code that calculates the Ingot Boxes distance and turns the shelf on/off based on that distance so it's very odd that it seems to make a difference for you, also the game won't automatically run any user commands, they are there for the user to manually enter if they encounter some known issues that may still be present.

I have a suspicion that somehow your save file hasn't Ticked Off on the 'Has Placed Shelf' checkbox when the Ingot Shelf Box was placed, which would lead to the shelf not being active upon loading.
So not only would I need your Save File to patch the resulting issue of the Shelf being bought, box Placed/Gone, but data not applied to say it's been Placed, to fix the issue you are facing, but also the ability to find why this happened and patch that part aswell so it doesn't happen to anyone else 🙂👍

**Comment by Tiberius-Ryx-Tyr** [comment]
Any way to manually give you my save?

**Comment by Tiberius-Ryx-Tyr** [comment]
![20240328195244_1](https://github.com/FuryFight3r/ScrappingSimulator/assets/165326221/105feedf-1c11-45ff-b917-07829c6475c5)

**Comment by FuryFight3r** [comment]
There is still some old fix code on the Buy Object from an early v0.27ish update that changed the Ingot shelves, that should let you buy it again (at no cost) to reactivate it, though it's still incredibly strange that it's not being turned on when loading, especially more so that the game knows that you've not only bought the item, but also placed it.

As the Bought/Placed variables should be the only 2 variables that determine whether or not to activate the shelf when loading and seeing as yours definitely states it's Both Owned and Placed it 'should' check all the boxes to be enabled on startup 🤔🤔

You can manually send in your save file to my support email: admin@defectgaming.com
If you are having issues with the in-game report feature, as this feature is only new as of the v0.37 update, yet I am still only getting the normal, discord/GitHub reports rather than the In-Game reports, so something may be wrong with that also, haven't had anyone besides myself test it at the moment, besides yourself as far as I know, so still got some kinks to work out with it I guess 😅

**Comment by Tiberius-Ryx-Tyr** [comment]
Are the Saves located in AppData not sure what files are the save or not

**Comment by FuryFight3r** [comment]
You should be able to click the 'Save File Directory' button on the Right hand side of the pause menu In-Game/On Main Menu to open the directory directly, however if that isn't working for you either (it's similar code to how the Generate Zip File button operates, so this may not work for you either) is so the directory is:
```
%AppData%/LocalLow/DefectGaming/Scrapping Simulator/
``` 
And the Save File will be named:

 ```
Scrapping_Simulator_Data.es3
```

The log files are also named:
```
Player.log
Player-prev.log
```

**Comment by Tiberius-Ryx-Tyr** [comment]
Ok thanks, Save Directory button works on the main menu at least

**Comment by FuryFight3r** [comment]
Hi again @Tiberius-Ryx-Tyr 
Thanks again for reporting this, I have just released a hotfix that will add a second check for the Ingot Shelf to make sure it's enabled If Purchased/Placed when loading, which should solve this issue for you :)
