### ISSUE TITLE
[Bug]: Grammatical errors  > New email notification text

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#16]
### Describe the bug

Current text:
You Recveived an eMail from ______ go to your PC to check it.

### Reproduction Steps

1. Wait until an email is recieved

### Expected behaviour

"You Recveived an email from _____ go to your PC to check it." < Original line.

Recveived should be received <uncapitalized and v would be removed.

(Suggested)
eMail < depending on your preference this could be email or e-mail. 

This statement seems like it should be two separate sentences. This could be divided across two lines so it appears as the following:

You received an email from _____.
Go to your PC to check it.

### Screenshot(s)/Video(s)

![email bug](https://user-images.githubusercontent.com/99054594/153480337-e1b73f04-6cd8-49dc-bb83-0c851969419d.PNG)

**Comment by FuryFight3r** [comment]
Hi JackDaring,
Thank you for pointing that out, I never even noticed :P
I will have that fixed in the next patch :)

**Comment by FuryFight3r** [comment]
This has been patched in v0.28.5, thank you for reporting this :)
