### ISSUE TITLE
[Suggestion]: <not sure if bug so did [Suggestion]:>

### ISSUE THREAD

**Issue by ShadoWarBlade** [FuryFight3r/ScrappingSimulator#167]
### What is your Suggestion?

when upgrade screwdrivers or pliers it makes a green box appear on the workbench which gets in the way of dismantling

![scrapping simulator bug](https://github.com/FuryFight3r/ScrappingSimulator/assets/168285422/2d102377-5482-481d-b094-1b083ba2680b)

### How will this suggestion fit into the Scope of Scrapping Simulator?

see above

### How would the Game and Community benefit from this suggestion?

see above

**Comment by ShadoWarBlade** [comment]
![2](https://github.com/FuryFight3r/ScrappingSimulator/assets/168285422/1e0ee537-642d-40c3-8acf-6631282b7749)

just so you know i bought second upgrade again and still had same issue

**Comment by FuryFight3r** [comment]
When purchasing items from the Hardware Store most will appear as a Cardboard Box next to the Front Counter the Box(es) will need to be returned home and placed in their respective spot

There is a bit of text when purchases that says this in brief, but it is commonly missed despite the red colour, in this next update I have implemented a little add-on to the tutorial that explains this further 🙂👍

**Comment by ShadoWarBlade** [comment]
ahh thanks ill check now thanks again -  now i feel dumb thanks mate for that it was annoying. i just realised i remember the text now but didnt see the small box on the floor lol

**Comment by FuryFight3r** [comment]
> ahh thanks ill check now thanks again -  now i feel dumb thanks mate for that it was annoying. i just realised i remember the text now but didnt see the small box on the floor lol

Glad you were able to get it working again, with this it's not so much an end user issue, more so that I've got to do a better job at explaining certain mechanics of the game within the tutorial 🙂
Happy Scrapping! 🙂👍
