### ISSUE TITLE
[Suggestion]: Mini games?

### ISSUE THREAD

**Issue by BobNuggets** [FuryFight3r/ScrappingSimulator#2]
### Suggestion;

I know you have a few ideas for mini games but was curious if you'd consider maybe something simple as well to do to kill time, like when you're waiting on ingots to cool etc, My suggestion is something like.. minesweeper or a simple game like that playable on your pc in the house. Gives you something to fiddle with while waiting on something else. 

### Why is this a good suggestion?

Mini games in general are a cool idea and I do love the beach combing idea with the metal detector and im also a huge fan of fishing considering like 15 of the games in my steam library are about fishing but, I think a mini game should also be just what it says on the tin, a mini game, something little that you could immediatley pull up and play with.

**Comment by FuryFight3r** [comment]
Hi BobNuggets, 
That is a great suggestion, I will certainly put it into consideration :)

**Comment by FuryFight3r** [comment]
Thank you for your great suggestion BobNuggets, in v0.28.3 I have implemented a very basic version of Mine Sweeper, called Mine Sweepin' which can be found on your PC under the Games folder :)
