### ISSUE TITLE
Ingots dont move

### ISSUE THREAD

**Issue by SpercWolf** [FuryFight3r/ScrappingSimulator#21]
### Describe the bug

When you put the solid ingot bars on the storage shelf in the garage and then save the game they are no longer able to be removed from the shelf to be sold. I have also noticed that you can double stack them within a shelf but there is a large gap between the bars so it looks like one is floating in mid air on the shelf.

### Reproduction Steps

1.) put an ingot bar on the storage shelf in the garage.
2.) save game
3.) try and remove the ingot bar from the shelf

### Screenshot(s)/Video(s)

![Screenshot (9)](https://user-images.githubusercontent.com/103287291/162527446-042a13f0-f69b-4cc3-9c76-995de25c7b81.png)

**Comment by FuryFight3r** [comment]
Hi there SpercWolf,
Thank you for reporting this 🙂 I will do some testing to see if I can replicate the issue, but either way I am thinking I may need to completely redo the shelving script, well, I think the shelving script is 'okay' it's just that when it's data gets saved and loaded there always seems to be some data loss or corruption happening between the Ingots and shelves.
I will do my best to fix the issue, if not the next update will remove all attached Ingots and drop them in the garage and temporarily remove the shelf, then I will be able to re-write the whole shelving script and have its data more properly suited for the Saving and Loading System which should remove the risk of players losing any ingots after redoing the script and then re-adding the Shelf

**Comment by FuryFight3r** [comment]
Hi again SpercWolf,
I just wanted to let you know that this issue should be fixed in the new v0.28.6 update, if you still have some ingots stuck in the shelf you may need to use the 'reset_shelf' command within the command panel (accessed by pressing the tilde [~] key) which should allow you to get the remaining bugged ingots free.
Thanks again for reporting this issue :)
