### ISSUE TITLE
[Bug]: DVD Player has CD Rom drives instead of DVD rom drives

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#26]
### Describe the bug

The DVD player has a CD drive instead of a DVD drive.

### Reproduction Steps

1. Find a DVD Player
2.  Open the lid of the DVD Player
3. Find a CD Drive.

### Expected behaviour

I expect to find a DVD drive in the DVD player or the multi-role "Optical Disc Drive."

Reference if helpful:
https://www.dell.com/support/kbdoc/en-us/000147805/guide-to-optical-disk-drives-and-optical-discs

**Comment by FuryFight3r** [comment]
Thank you for the suggestion, I had just made it a CD drive for simplicity sake, but could certainly add a DVD Drive to be more realistic 🙂

**Comment by FuryFight3r** [comment]
Hi there Jack, I have since added the DVD Drive as a Variant of the CD Drive in the [v0.30.4 Update](https://store.steampowered.com/news/app/1496640/view/3395168821446701708) which has a few different parts and is a little more valuable than that of a CD Drive.
Thanks again for reporting this 👍
