### ISSUE TITLE
[Bug]: 2 crucibles after loading (from earlier version), what do i do?

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#28]
### Describe the bug

![image](https://user-images.githubusercontent.com/101810723/175137328-ee202d0b-9438-4ca4-ac12-b188a8adf089.png)
uhh yeah, i don't think this is right. i can't take out the second one, it's stuck in there and is an actual crucible. do i have to restart? everything else is fine.

**Comment by aus2004** [comment]
saving and loading seems to be uh
![image](https://user-images.githubusercontent.com/101810723/175175809-95561fd3-90aa-4143-ba9b-f5182e3e26c9.png)
yeah that's not looking too good

**Comment by FuryFight3r** [comment]
To access your save file you will need to access your appdata folder, it will be under AppData/LocalLow/DefectGaming/Scrapping Simulator, the es3 file is your save file 🙂

However I have managed to reproduce this error and I believe I have created a fix for it, I will finish up with a few other bugs that have popped up and hopefully have a small HotFix update out very soon :)

**Comment by Diesel3879** [comment]
i have a issue with the crucible.i bought 1 and when i went home to the garage it is not there and it is not in the bug box in the bedroom and when i am looking at them in the store it says i own 1 but when i hit esc click on bug fixes then click on return crucible it says that i do not own a crucible what is going on?

**Comment by FuryFight3r** [comment]
> i have a issue with the crucible.i bought 1 and when i went home to the garage it is not there and it is not in the bug box in the bedroom and when i am looking at them in the store it says i own 1 but when i hit esc click on bug fixes then click on return crucible it says that i do not own a crucible what is going on?

Hi there Diesel3879, Thank you for reporting this, This is linked to the duplicate issue with the Crucible, I will have a hotfix coming out very soon that addresses these issues :)

**Comment by FuryFight3r** [comment]
Hi there aus2004,
This issue has now been fixed in the v0.30.1 Hot Fix.

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.
