### ISSUE TITLE
[Bug]: prop flying?!

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#29]
### Describe the bug

you can fly in midair with ewaste until you hit the bug box on the top of the map

### Reproduction Steps

grab a large object, preferrably a computer or server. Put it near the ground and run and jump towards it. you'll suddenly start flying. Alternatively, put it on it's side against a wall, grab it from below you after jumping up onto it and face into the wall, then spam jump.

### Expected behaviour

i dunno, you're not supposed to fly

### Screenshot(s)/Video(s)

https://www.youtube.com/watch?v=A5P7GeVLQzM (it's too big :frowning:)

**Comment by FuryFight3r** [comment]
Hi there aus2004,
I am currently working through some solutions for this, one solution is to make it so when the player is walking it either adds more force to the object, hopefully keeping the object a bit further away from the player, or make it so the objects lock to the carrying position while moving and only have the springing/smooth movement while standing still (this would also help with the horrid jittery look of the object while moving).

Long term goal, I would like to entirely rework the objects to be dummy/empty objects that do not have all the parts until they are added to the disassembly table, this way I can disable collisions between the object and the player while carrying, without having to manually disable/enable all the inner colliders on the inner parts.

Nevertheless I will see about creating a temporary solution in the v0.30.1 HotFix 

Thanks again for reporting this issue 🙂

**Comment by FuryFight3r** [comment]
Hi there aus2004,
This issue has been improved upon in the v0.30.1 Hot Fix.

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.
