### ISSUE TITLE
[Suggestion]: Action Queue

### ISSUE THREAD

**Issue by cyndercrys** [FuryFight3r/ScrappingSimulator#3]
### Suggestion;

I was wondering if there was a way to queue actions, like being able to have 2 or 3 actions in a row so I'm not clicking all over the place. Thinking specifically for the shorter pieces, like taking out RAM sticks or unscrewing screws. Actions that take like 1-2 seconds. 

### Why is this a good suggestion?

To be honest, taking out screws is my least favorite part. Maybe it's because I detest it so much irl, but taking out screws is just...annoying to me. Personally I think it'd be easier, maybe a bit more enjoyable, if there was like an action queue or even a "remove all screws" action (though that last one is just wishful thinking on my part). 

I know it's part of the game, and I love the game all the same, but screws... I will never like screws.

**Comment by FuryFight3r** [comment]
Hi Cyndercrys,
That is a great suggestion, it has been suggested before a few times, though I haven't been able to figure out a way about going about it, as its a first for me (coding a queuing system) but I will certainly have a go at implementing something like this, it certainly wont be as OP as one click removes all screws (though that could be a perk to have for mid/end-game rewards), though I will try make something that you can at least queue up a few screws as I can understand that these are the least enjoyable part to pull off, so at least having a queueing system for the screws to start off with would be a great start :)

**Comment by FuryFight3r** [comment]
Thank you for a great suggestion Cyndercrys, this has now been implemented into the v0.28.3 update :)
