### ISSUE TITLE
[Bug]: stuck spot

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#30]
### Describe the bug

basically i found a spot that can get you stuck, nothing special but this one is really easy to get to accidentally

### Reproduction Steps

go into the hardware store.
get on top of the brownish-pink boxes next to the stand, walk into the wall, you will start sliding with no way to get out.
fiddle around a bit. you'll pop up onto the shelving next to them.

### Expected behaviour

i think you should just be able to walk on the brownish-pink boxes without this happening

### Screenshot(s)/Video(s)

https://www.youtube.com/watch?v=K4MCUPkcfAc (too big again :frowning_face:)

**Comment by FuryFight3r** [comment]
Hi there aus2004,

Thanks for reporting this, I had no idea that was even a thing, I should be able to fix that easily :)

**Comment by FuryFight3r** [comment]
Hi there aus2004,
This issue has been fixed in the v0.30.1 Hot Fix.

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.
