### ISSUE TITLE
[Bug]: trolley bugs

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#31]
### Describe the bug

bugs included:
trolley clipping
getting the trolley stuck
floating trolley
clipping out of bounds with the trolley
falling out of the world with the trolley and not hitting any bug boxes
the settings tab opening every time you open the pause menu

### Screenshot(s)/Video(s)

https://www.youtube.com/watch?v=yXdPUZugiO0 (6 minutes, oh boy)

**Comment by FuryFight3r** [comment]
Hi again aus2004,
Thank you for reporting this, I had some idea that the trolley was janky but hadn't realised it was that bad :P I will make some modifications to the way the Trolley works and hopefully stop most of these bugs :)

**Comment by FuryFight3r** [comment]
Hi there aus2004,
This issue has been improved upon in the v0.30.1 Hot Fix.

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.
