### ISSUE TITLE
[Bug]: more crucible problems!

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#34]
### Describe the bug

alright, so i'm gonna test some crap out about what is going on here and i'll say what is wrong about it, but i can tell you it looks horrific, this is once again me loading a save

alright, other than just the looks this crucible doesn't seem to register in the forge. (image below)
![image](https://user-images.githubusercontent.com/101810723/175802482-2db0d30a-4e63-4ed8-bdc7-72d3c66707a7.png)

you can still put stuff in it, and other than that it seems fully functional.

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/175802423-16c57e30-b863-4d58-8b3f-322b0222cb19.png)

**Comment by FuryFight3r** [comment]
Hi there aus2004,
Thanks for reporting this, that one is a weird one, I did however leave a debugging command in 'reset_crucible' which I believe will solve the issue you are having, It seems to be that the LODs (Level of Details) have become corrupt so all (High Quality, Mid Quality, and Low Quality versions) are now visible no matter your distance from the object, which usually would only happen when going from a new game version, back to an old game version (from v0.30 to v0.28.6 for example) but it has sometimes happened on random occasions when going to a new version also. but hopefully the 'reset_crucible' command works in your case

**Comment by aus2004** [comment]
![image](https://user-images.githubusercontent.com/101810723/175802797-dd91dc00-2708-43f5-a7e4-aa455c939eb3.png)
oh dear not this again
anyway at least the forge is usable now

**Comment by aus2004** [comment]
oookay so the crucible is just all kinds of broken

**Comment by FuryFight3r** [comment]
Hmm, yeah that is all kinds of wacked, are you able to provide your save-file so I can look into the Logs to see what is going wrong? I can see visually in the screenshots that something is certainly broken, but am unable to determine what that is without the logs, also having your save file will allow me to create a fix for the exact error and similar errors that could arise - if not by pressing [F5] will show the Log Handler, which you can safely ignore most if not all of the grey/white Logs, but any Red errors may be an indicator as to what went wrong and where (you may need to click on any Red Logs to open the up fully and display all information

**Comment by aus2004** [comment]
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <d4cde64232cf45659d86aafa597faa77>:0)
referenceManager.repairCrucibleV30 () (at <df82771bab484334b31301730cda0eb1>:0)
testingEnhancer.activateCommand () (at <df82771bab484334b31301730cda0eb1>:0)
testingEnhancer.Update () (at <df82771bab484334b31301730cda0eb1>:0)

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <d4cde64232cf45659d86aafa597faa77>:0)
referenceManager.repairCrucibleV30 () (at <df82771bab484334b31301730cda0eb1>:0)
testingEnhancer.activateCommand () (at <df82771bab484334b31301730cda0eb1>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c6a0be87269c4a56aa4c8bc00101797f>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c6a0be87269c4a56aa4c8bc00101797f>:0)
UnityEngine.UI.Button.Press () (at <f0aaf29b79984897ab11d054cc39fbad>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <f0aaf29b79984897ab11d054cc39fbad>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <f0aaf29b79984897ab11d054cc39fbad>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <f0aaf29b79984897ab11d054cc39fbad>:0)
UnityEngine.EventSystems.EventSystem:Update()

IndexOutOfRangeException: Index was outside the bounds of the array.
crucibleScript.removeMetalFromCruc () (at <df82771bab484334b31301730cda0eb1>:0)
mouldScript.onAddIngot () (at <df82771bab484334b31301730cda0eb1>:0)
mouldScript.OnCollisionEnter (UnityEngine.Collision other) (at <df82771bab484334b31301730cda0eb1>:0)

here's the bugs according to the game and
https://drive.google.com/file/d/1KW4VzGK7Xl27LFl3Nb9YybjTQG_7RJS_/view?usp=sharing my personal save.

**Comment by FuryFight3r** [comment]
Thank you for that, there is certainly something funny going on, I will look into this and hopefully have a fix out asap

**Comment by FuryFight3r** [comment]
Hi there aus2004,
Thanks again for reporting this issue, it has now been fixed in the v0.30.2 Hot Fix :)
https://store.steampowered.com/news/app/1496640/view/3358011588184373380
