### ISSUE TITLE
[Bug]: Queue Bug

### ISSUE THREAD

**Issue by CrazyJamie1** [FuryFight3r/ScrappingSimulator#35]
### Describe the bug

I broke the queue, I managed to fix it by putting another item on the table, and pressing F to leave it.

### Reproduction Steps

1. Have a small ram from the laptop, the one with 4 on each side,
2. have cleared the ram from almost everything but the sides
3. have about three notches left, have them queued
4. but click on the ram it self before finishing the queue

### Expected behaviour

Having a pop up about child object

### Screenshot(s)/Video(s)

![Bug q](https://user-images.githubusercontent.com/108179614/175829705-2e5c2755-646f-41bb-a55e-6b963a1f8b54.JPG)

### Console output

![Bug maybe](https://user-images.githubusercontent.com/108179614/175829718-69d260e6-d412-4398-8523-b2376a8bbbba.JPG)

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8987302/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8987303/Player-prev.log)

**Comment by aus2004** [comment]
there's a similar bug that occurs when you just really use the hell out of the queue, it'll grab the wrong items and sometimes a single item will stay even when everything is taken apart.

**Comment by FuryFight3r** [comment]
Hi there CrazyJamie,
Thank you for reporting this, I think I understand what is going wrong, I will look into this and see what's going on
