### ISSUE TITLE
[Bug]: Floating/Stuck Item when Grabbing

### ISSUE THREAD

**Issue by Merlin8326** [FuryFight3r/ScrappingSimulator#37]
### Describe the bug

When picking up items - it sticks and cannot be dropped to pick up next item. Carry it and it moves down to lower area and causes you to float. 

### Expected behaviour

being able to reset item that you grab to drop it regardless if u have picked it up or not. 

### Screenshot(s)/Video(s)

![Stuck item grab](https://user-images.githubusercontent.com/104960575/176986745-40ee5040-bf01-454e-bcfc-e53a75cdfd6e.png)

### Player Logs

[Can't Send ES3.txt](https://github.com/FuryFight3r/ScrappingSimulator/files/9032437/Can.t.Send.ES3.txt)

**Comment by FuryFight3r** [comment]
Hi there Merlin, I will look into this and see if I can reproduce it, are you able to explain further what is actually happening? or provide a video showcasing what you mean? I am struggling a little understanding what is actually going wrong, does it only happen with small objects or everything?

**Comment by Merlin8326** [comment]
So far. It is everything from SSDs to Ingots to Chemicals. The SS is of me having a RAM stick in my hands. And having to look downward to see it.

**Comment by FuryFight3r** [comment]
That is certainly very strange,are you able to provide either your save file or a copy of your Logs, I have tested this with a few other saves (your old one that you had sent a while back also) and didn't come across this issue, is it just picking up any object gets stuck every time? Or does it need to be spammed?

**Comment by FuryFight3r** [comment]
Hi there Merlin,
I have added the 'reset_carry' command to the command panel which should fix the issue if anything is stuck to the player, this command, runs through ever object that can be carried and forces it to be dropped. I was unable to replicate this issue or find the cause of it, so hopefully this temporary fix helps you while I attempt to find the root of the issue.
Thanks again for reporting this 🙂
