### ISSUE TITLE
[Suggestion]: Add additional storage or large vault

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#39]
### Suggestion;

As my garage slowly fills with gold bars and other precious metals. It would be nice to put them in a large secure vault of some sort. 

Beyond that, though an additional steel shelf would be nice to store quantities of different types of ingots.

### Why is this a good suggestion?

It would be nice to have more storage.

**Comment by FuryFight3r** [comment]
Hi Jack,
Thank you for another great suggestion, something along these lines is being planned for the future, I was thinking of adding a 4th shelf to the current Ingot Shelf to allow storage of all Base Material Ingots (Iron, Alum, Brass, Copper) and I was thinking of adding some type of Safe or Vault for the 100g & 1kg Gold Silver Ingots. As I am not really a fan of how the 100g ingots have gaps when being added to the Main Shelf, so I wanted to add something that is specifically used for precious Ingots

**Comment by FuryFight3r** [comment]
Hi there @JackDaring thank you again for this suggestion, I had added this a couple of updates ago but forgot to mark this off as complete 😅👍
