### ISSUE TITLE
[Suggestion]: Adjust minesweeping to be logic based

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#42]
### Suggestion;

I'm familiar with the original minesweeper this seems to be taken from and in that game the numbers were important so that you could determine how close you were to an actual mine and flag it. 

This version seems entirely luck based and I'm not sure I would approach getting the achievement for it.

I'd recommend making the numbers be more relevant to the placement of the bombs like the original game this is based on.

### Why is this a good suggestion?

It would be nice if this wasn't just luck based.

**Comment by FuryFight3r** [comment]
Hi Jack,
Thank you for your great suggestion, I did tinker with this a little when attempting to make this mini-game, however it proved very difficult and the only way that seemed plausable was to either make it Seed Based Generation (which I have never worked with as of yet) or creating a bunch of pre-determined outcomes for it to pick between (which could be learnt and abused), nevertheless I do intend on reworking the current and adding extra mini-games into Scrapping Sim 🙂

**Comment by FuryFight3r** [comment]
Thanks again for Suggesting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) as I have implemented a 'Hint' system that cuts out the RNG side of things 🙂👍
