### ISSUE TITLE
[Bug]: Plastic bottle stat resets between game loads

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#44]
### Describe the bug

When exiting and reloading the game. The plastic bottle count appears to reset to 0. 

This is problematic when going after the spare no expense achievements.

### Reproduction Steps

1. Pick up some bottles from some trash cans.
2. Confirm the counter is adding the bottles to your stats screen
3. Save the game
4. Exit the game
5. reload the game and look at the stats screen under plastic bottles

### Expected behaviour

I expect when reloading the game to maintain my stats for plastic bottles picked up.

**Comment by FuryFight3r** [comment]
Hi Jack,
Thank you for reporting this, the bottles should save with all the rest of the values within the player stats, however I will look into this have have a patch for it next update 🙂

**Comment by aus2004** [comment]
yeah i thought it was intentional considering the whole _secret_ achievements involving them
