### ISSUE TITLE
[Bug]: When dissasembling the HDD it's possible to pull two drive platters out at a time.

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#45]
### Describe the bug

When disassembling an HDD you need to alternate between removing the drive platter and the drive platter arms. It's possible once below the initial drive platter arm to pull two plates out at once. You can't continue removing additional platters until you remove at least one of the arms.

### Reproduction Steps

1. Get an HDD
2. Begin disassembling it
3. Once you remove the first drive platter arm attempt just to remove drive platters
4. Observe the bug, or repeat step 3 until it occurs.

### Expected behaviour

The drive platter and arms should be removed in an alternating fashion.

### Screenshot(s)/Video(s)

![drive platter arms](https://user-images.githubusercontent.com/99054594/177269376-f1fd4fbc-742e-4d6d-99a3-058c535344f8.PNG)

**Comment by FuryFight3r** [comment]
Hi there Jack,
Thanks for reporting this, I will have it fixed within the next update :)
