### ISSUE TITLE
[Bug]: Scrap market inventory measurements are incorrect/inconsistent with inventory

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#46]
### Describe the bug

When looking at the scrap market interface the values in the inventory column do not match the values in the personal inventory. 

This is primarily due to the KG vs G measurements.

In the example images, I have 5281.8g or 11.6 pounds of iron ore in my personal inventory.
The scrap market says I have 52.82kg or 116 pounds of iron ore.

This appears to be the case for waste and silver as well. 

### Reproduction Steps

1. Acquire iron, waste, or silver in your personal inventory.
2. Go to the scrapyard interface
3. Compare values between the interface and your personal inventory for consistency.

### Expected behaviour

All measurements for materials should be uniform in value between all inventory panels.

### Screenshot(s)/Video(s)

![1](https://user-images.githubusercontent.com/99054594/178760872-b3e52dc4-af64-4cc6-9213-613384406bda.PNG)
![2](https://user-images.githubusercontent.com/99054594/178760875-7d260b6e-687b-408a-84f0-8340616abbeb.PNG)
![3](https://user-images.githubusercontent.com/99054594/178760877-0d378454-c82a-40f6-86cd-1992d1718db6.PNG)

**Comment by FuryFight3r** [comment]
Hi there Jack, 
Thank you very much for reporting this, I have no idea how I overlooked this 😅 but will have it fixed asap nonetheless 🙂

**Comment by FuryFight3r** [comment]
Hi there Jack, Thanks again for reporting this issue, it has since been fixed in the [v0.30.4 Update](https://store.steampowered.com/news/app/1496640/view/3395168821446701708) 👍
