### ISSUE TITLE
[Suggestion]: Add improved render distances in options

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#47]
### What is your Suggestion?

When wandering around the neighborhood objects like the fences switch from their resource-saving solid to resource-intensive model textures in front of me. It would be nice if this was not as obvious to me as I believe my setup is capable of handling the renders.

If this could be adjusted in the settings via a render distance option that would be nice.

I've included an image showing the fence mid-render
![4](https://user-images.githubusercontent.com/99054594/178763226-8166b23e-493c-42ff-8838-16a456b609f5.PNG)
 as an example.

### How will this suggestion fit into the Scope of Scrapping Simulator?

Immersion

### How would the Game and Community benefit from this suggestion?

It would be a nice quality of life feature for those with more robust systems.

**Comment by FuryFight3r** [comment]
Hi there Jack,
I have since Implemented the 'Insane' Option on both Shadow Distance and LOD Distance on the [v0.30.4 Update](https://store.steampowered.com/news/app/1496640/view/3395168821446701708) which should look a lot more appealing.
Thanks again for suggesting this 👍
