### ISSUE TITLE
[Bug]: CD Drive Goes Invisible

### ISSUE THREAD

**Issue by Poonfury** [FuryFight3r/ScrappingSimulator#5]
### Describe the bug

I take apart a CD drive like normal, but when I click on the last part (the casing) is disappears like normal.  When I try to place the next item on the disassembly table it wont snap into position.  I notice that the CD dive is still there, just invisible.  I can pick it up and drop it somewhere else and then the Disassembly table works.  After a save and reload all of the invisible CD drive are back and I can disassemble them again, resulting in the bug to repeat itself.  I could get parts from infinite CD drives.

### Reproduction Steps

1.  Take CD drive from parts box. 
2. place CD drive on disassembly table.
3. Take CD drive apart as normal.
4. Click the last piece, CD drive disappears.
5. When looking at table tool tip for CD drive appears on screen.
6. Move bugged CD drive out of the way.
7. Save game and exit.
8. Load save.
9. CD drive is now visible in the location left before save and exit.

### Expected behaviour

Expect CD drive to go away once last piece is removed.

### Screenshot(s)/Video(s)

![20220122195937_1](https://user-images.githubusercontent.com/47801250/150660554-49fd4c84-bfe0-47cc-b524-dfb12cb74fbb.jpg)
![20220122195943_1](https://user-images.githubusercontent.com/47801250/150660558-03bef20e-3d63-44fb-9510-7f1184a94264.jpg)
![20220122195952_1](https://user-images.githubusercontent.com/47801250/150660561-ce095a86-6bac-446b-a833-6b38b2c0871e.jpg)

### Console output

Unable to remove LOD0 as it is not in the List

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7919566/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7919567/Player-prev.log)

**Comment by FuryFight3r** [comment]
Thank you for reporting this, I will get onto fixing it right away

**Comment by FuryFight3r** [comment]
I have fixed this issue and released it under the same version of v0.28.3, Thanks again for reporting this and making a nice detailed report :)

**Comment by Poonfury** [comment]
Not sure if it's related, but since the patch (awesome response time BTW!) the CD drive behaves properly, but I get a bunch of these messages in the console: Renderer 'ScrewHD' is registered with more than one LODGroup ('StagedCDDrive(Clone)' and 'Screw').

**Comment by FuryFight3r** [comment]
Ah thank you for that, I have a feeling I know what is causing the Screw LOD issue, I will try find what is causing this and have a patch out asap :)
