### ISSUE TITLE
Text wont go away

### ISSUE THREAD

**Issue by bradfordcdavis** [FuryFight3r/ScrappingSimulator#50]
### Describe the bug

After visiting the scrap vendor I get the text for 1k silver that wont go away. until I reload the game.

### Reproduction Steps

1 go to vendor
2 hover mouse over materials
3 close window

### Expected behaviour

text wont go away

### Screenshot(s)/Video(s)

![Bug 1](https://user-images.githubusercontent.com/20309855/180585385-3d7c47b8-4d95-4604-b4be-fad3c5480729.jpg)

**Comment by FuryFight3r** [comment]
Hi there Bradfordcdavis, 
Thank you for reporting this, I will look into it and should have it fixed in the next update :)

**Comment by FuryFight3r** [comment]
Hi again Bradfordcdavis,
This bug has now been fixed in the [v0.30.5 Update](https://store.steampowered.com/news/app/1496640/view/3395170090042395241)
Thanks again for reporting this issue 🙂
