### ISSUE TITLE
disk player is invisible (the one in the pc)

### ISSUE THREAD

**Issue by bradfordcdavis** [FuryFight3r/ScrappingSimulator#51]
### Describe the bug

After taking apart the disk player. I click on it and it seems to work. When I go to put another eWaste on the desk it wont auto land on the desk. I put eWaste down and look at the desk and the text for the cd player comes up like it is still there. You can even press e on it but you can't do anything. What I have decided to do is pick up the invisible player and put in the bug box. It doesn't happen all the time.

### Reproduction Steps

1 take apart cd player

### Expected behaviour

item will disappear but still be there

**Comment by FuryFight3r** [comment]
Hi there Bradfordcdavis,
Thanks for reporting this, I think I know what is going on with this, I believe it may be the new method of adding objects to the table may be conflicting with something and remaining active, I will look into this and should have it fixed in the next update :)

**Comment by FuryFight3r** [comment]
Hi again Bradfordcdavis,
This bug has now been fixed in the [v0.30.5 Update](https://store.steampowered.com/news/app/1496640/view/3395170090042395241)
Thanks again for reporting this issue 🙂
