### ISSUE TITLE
[Bug]: items can get stuck under crucible if bought at the wrong time

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#53]
### Describe the bug

basically if you buy the crucible while stuff is in that corner it'll get stuck under it.

### Reproduction Steps

simply place a laptop where the crucible will be. then purchase it.

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/183266793-db4eebf4-f1ab-4b2e-b6af-8ac3cb5606dc.png)

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this, I should be able to fix this by adding a bug box collector under the Furnace Bricks 👍

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)
