### ISSUE TITLE
[Bug]: the bug box is still where the chemical table is

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#54]
### Describe the bug

the bug box for the beaker is there even before you buy any of it. This means throwing an object in it's direction yeets an object to the bug box without reason.

### Reproduction Steps

throw an e-waste object at the spot where the beakers would be.

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/183266850-d45f0fca-94aa-4f31-8a34-0750b55ea182.png)

**Comment by FuryFight3r** [comment]
Hi Aus,
Thank you for reporting this, I will attach the bug box collector to the beaker itself so it's only active after buying the beaker, then again this collector could probably be removed anyway as it should be nearly impossible for objects to get stuck inside the beaker now with the new carrying mechanic 🙂

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)
