### ISSUE TITLE
[Bug]: certain animations don't play

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#57]
### Describe the bug

Certain animations for chips don't play, mostly relating to the gold connectors. The network chip has this issue.

### Reproduction Steps

find the network card and have a look at it's gold connector. it has a removal time of 0 seconds compared to the usual 0.95, trying to remove it will make it go to it's default position on the table for a frame and then disappear.

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this, I will have a look into this and see what is going wrong 🙂

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)
