### ISSUE TITLE
[Bug]: Skill progress bars do not scale properly

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#58]
### Describe the bug

the skill progress bars do not relate to the percentage of completion of the skill itself sometimes. i have no clue what causes this.

### Reproduction Steps

It's very obvious just by opening the skill levels menu and doing math

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thanks for reporting this,
I am a little unsure of what you mean by this, the XP bars work in a similar fashion to that of Runescape/Melvore whereby the first level is, for example from 0xp to 80xp so the XP bar would indicate a minimum value of 0 and a maximum value of 80 (0xp being 0% full, and 80xp being 100% full) then after levelling up the skill the bar resets and the minimum value would now be 80 and the maximum 160 (80xp being 0% full and 160xp being 100% full) for example.
Would you happen to have a screenshot of this occurrence? As I hadn't come across this during my testing where I had maxed out each skill and hadn't noticed anything out of the ordinary.
Nevertheless I will look into this and see if I can find and fix the issue. 🙂

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)
