### ISSUE TITLE
[Bug]: Storage Buckets Disappeared & Still Counted

### ISSUE THREAD

**Issue by dancrodev** [FuryFight3r/ScrappingSimulator#59]
### Describe the bug

'Raw Material Storage Bucket' disappears if placed in the same area as 'Treated Wooden Table' before the table is purchased. Upon purchase of the table, the storage bucket has disappeared, but is still counted in the hardware store.

### Reproduction Steps

1. Purchase 'Raw Material Storage Bucket'
2. Place it where the 'Treated Wooden Table' will spawn in the garage on purchase
3. Buy the 'Treated Wooden Table from the hardware store'
4. Return to garage to see the 'Treated Wooden Table' is now present, but the storage bucket is gone
5. Return to the hardware store and see that the # of storage buckets is still accurate (not decremented due to glitch)

**Comment by dancrodev** [comment]
If you need me to share screens and replicate, please reach out to me in the DefectGaming Discord, user "Xen#1687"

**Comment by FuryFight3r** [comment]
Hi there Dancrodev,
As per our discussion on discord, for anyone else having this or a similar issue of any 'Carry-able' object(s) disappearing, the Bug Box within the bedroom should hopefully have triggered an out of bounds event transporting the object back to the Bug Box 🙂 
If the object is trapped in an unretrievable location please do let me know so I can add a Bug Box collider there to collect the trapped object 🙂
