### ISSUE TITLE
[Bug]: Aluminum Ingot Unsalable on Metal Trades PC

### ISSUE THREAD

**Issue by Poonfury** [FuryFight3r/ScrappingSimulator#6]
### Describe the bug

I drop an aluminum ingot onto my computer screen and is disappears. When I go to the Browser.exe and then Metal Trades Icon for aluminum ingot is not there. Only an Icon that reads title, price, sell.  If I click sell it goes away, but I receive no money. Lose aluminum ingot.

No red error in console, will add messages for adding and selling on Metal Trades.

### Reproduction Steps

1. Place aluminum ingot at monitor and it disappears into the computer like normal.
2. activate PC.
3. click browser.exe
4. click metal trades.
5. aluminum ingot icon not there.
6. click sell on icon that reads title price.
7. icon goes away. no money added to my balance.

### Expected behaviour

Expect to see icon that reads aluminum ingot and the sell price.  Expect to be credited money once sold.

### Screenshot(s)/Video(s)

![20220122201153_1](https://user-images.githubusercontent.com/47801250/150660938-f170f2e9-ba5a-4ba1-bd63-6768790708d5.jpg)
![20220122201214_1](https://user-images.githubusercontent.com/47801250/150660940-bada4f0d-49b5-43fb-82df-6fa0b9e8dc9b.jpg)
![20220122201653_1](https://user-images.githubusercontent.com/47801250/150660942-ca930374-efd9-4c4c-b6d5-096c63d33349.jpg)
![20220122201726_1](https://user-images.githubusercontent.com/47801250/150660944-28832586-a399-4e83-aeff-071bd2d649a2.jpg)

### Console output

Removed object from the Object Reference List, the List now contains 33 Objects.
Added 1x Ingot to the PC Ingot Reference List, Currently 1x Ingots are active in the List.
Removed object from the Object Reference List, the List now contains 32 Objects.
Added 1x Ingot to the PC Ingot Reference List, Currently 2x Ingots are active in the List.
Removed Ingot from the PC Ingot Reference List, the List now contains 1 Ingots.
Removed Ingot from the PC Ingot Reference List, the List now contains 0 Ingots.

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7919576/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7919577/Player-prev.log)

**Comment by FuryFight3r** [comment]
This is a strange one, I will have a look into this and see if I can find what is happening, thank you for reporting this

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, I have just released a small patch fixing this issue, thank you for your detailed report :)
