### ISSUE TITLE
[Suggestion]: Scroll alternative

### ISSUE THREAD

**Issue by olix80** [FuryFight3r/ScrappingSimulator#60]
### What is your Suggestion?

From quite a while I have problem with my mouse (it's not Scraping sim issue) that my scroll went metally insane, so some players I think wil have sometimes same issue bacause let's be honest, money doesn't grow on tress, so please make an alternative for scroll for example keys "x,z" or "y,u" something like that, that doesn't break the gameplay.

### How will this suggestion fit into the Scope of Scrapping Simulator?

It's key suggestion not content one.

### How would the Game and Community benefit from this suggestion?

It's sometimes easier to use keys then scroll. Ease of zooming.

**Comment by FuryFight3r** [comment]
Hi there olix80,
Sure I should be able to implement something like that 🙂

**Comment by FuryFight3r** [comment]
Hi there olix80,

This has been added in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for suggesting this :)
