### ISSUE TITLE
RAM for Servers

### ISSUE THREAD

**Issue by bradfordcdavis** [FuryFight3r/ScrappingSimulator#61]
### Describe the bug

I am not able to remove the RAM in the servers. I even restarted and the same thing happened the next time I got a server.

### Reproduction Steps

get a server
try to remove the RAM

### Expected behaviour

You wont be able to remove the RAM

**Comment by FuryFight3r** [comment]
Hi there bradfordcdavis, 
Thank you for reporting this, I will have a look into it and hopefully have it fixed asap.

**Comment by FuryFight3r** [comment]
Hi again Bradfordcdavis,
I have just uploaded a silent update attached to the [v0.30.6 Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488)
Thanks again for reporting this :)
