### ISSUE TITLE
[Bug]: (visual) green sparkling effect of queued parts are offset

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#65]
### Describe the bug

Basically some parts have an offset sparkle from the queue indicator, i've noticed this only on crystal oscillators so far, but there may be more.

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/189412234-88452ee8-5422-409e-87bb-7a9aa2a51b80.png)

**Comment by FuryFight3r** [comment]
Hi there Aus, 
Thank you for reporting this, I will have a look into this, I have an idea on what could be causing this, but should be a simple fix 🙂

**Comment by FuryFight3r** [comment]
Hi there @aus2004
Thanks again for reporting this, It has now been patched in the [v0.31 Major Update](https://store.steampowered.com/news/app/1496640/view/3419948145834477881) :)
