### ISSUE TITLE
[Bug]: (visual) green sparkling effect may stay even when the object is currently active

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#66]
### Describe the bug

i'm not sure what causes this but even though it's the only thing currently active, the queue sparkle still stays.

(top left corner of image, compare to bottom right where the queue list should be)

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/189412558-d3da2873-4aff-44d6-a5a5-3f063200a31c.png)

**Comment by FuryFight3r** [comment]
Hi there Aus, thanks for reporting this.
I am a little unsure of what you mean by this one, was the sparkle enabled when adding the object to the queue, but the object never got removed? 
Or was the sparkle active the moment you pulled the lid off?
Or is the sparkle attached to an object that has already been disassembled, but the sparkle is still active?
I will see if I can replicate this issue and hopefully have a patch out asap 🙂

**Comment by aus2004** [comment]
the sparkle is never removed when the object is activated in the queue, so if the object is playing it's animation, the sparkle stays, which looks kind of jarring

**Comment by FuryFight3r** [comment]
> the sparkle is never removed when the object is activated in the queue, so if the object is playing it's animation, the sparkle stays, which looks kind of jarring

Ahh I am with you now, I completely agree, I was not too impressed with how it looked with the object Animating and the Sparkle staying both Active and Stationary while the Component was being removed, I was unable to add the Sparkle directly to the Animated part of the object as this generally has size modifications which I found warped and distorted the sparkles, I could possibly see about the Sparkle only staying active while it's within the Queue, once it gets removed from the queue and is now actively being removed I could disable the sparkle then which I think would look a lot less jarring 🙂

**Comment by aus2004** [comment]
yes, it would be a good compromising as it wouldn't look so weird anymore, plus it would indicate better which part was currently being activated

**Comment by FuryFight3r** [comment]
Hi again Aus,
I have since fixed this issue within a small Hotfix Patch for [v0.30.7](https://store.steampowered.com/news/app/1496640/view/3328745165988370115)
Thank you for reporting this :)
