### ISSUE TITLE
[Bug]: Metals Not Heating In Furnace

### ISSUE THREAD

**Issue by MrJohnnyB82** [FuryFight3r/ScrappingSimulator#7]
### Describe the bug

Metals added to crucible sometimes do not heat up when furnace is lit.  I discovered that taking out the crucible and putting it back in will fix issue and metals will heat up.  Not sure what causes this to happen, but I think its when you save and load with the crucible still in the furnace.  No error messages in console.

### Reproduction Steps

1. Access furnace with F key
2. Add metal of any type.
3. set gas level and light furnace
4. metal temperature does not change from zero
5. open furnace
6. remove crucible
7. replace crucible in furnace
8. close furnace
9. set gas level and light furnace
10. metal temp increases as normal

### Expected behaviour

Metal temperature to increase when furnace is lit.

### Screenshot(s)/Video(s)

![20220123093357_1](https://user-images.githubusercontent.com/47801250/150683845-b16bb60a-1a81-4c2e-a7bf-4e0abdaaee7a.jpg)

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920682/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920683/Player-prev.log)

**Comment by FuryFight3r** [comment]
Thank you for reporting this, I will have a look into why this is happening :)

**Comment by FuryFight3r** [comment]
Thank you again for reporting this, it has since been fixed in v0.28.4 :)
