### ISSUE TITLE
[Bug]: (visual) motherboard in television always goes to origin before playing it's animation

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#71]
### Describe the bug

the motherboard in the television always does this. It's weird.

### Screenshot(s)/Video(s)

https://user-images.githubusercontent.com/101810723/189454226-cf227ea5-ed2f-4bcb-9b6e-4ab48b5a8a0e.mp4

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this, I think It is a similar problem to the Gold Corner BGA Chip Animation Issue where the prefab for the MOBO is causing issues (as this MOBO is a variant of the PC MOBO prefab which I believe the TV is for some weird reason inheriting the PC MOBOs animation and not playing its own animation). This should be a simple fix, I will try have a HotFix out asap that touches of a lot of the issues you've brought up today, thank you for helping make the game better for everyone 🙂👍

**Comment by aus2004** [comment]
You are very much welcome. I enjoy finding bugs and glitches in the games i play, because i'm just a natural at it. I like this game's concept and wish to see it flourish.

**Comment by FuryFight3r** [comment]
Hi there @aus2004
Thanks again for reporting this, It has now been patched in the [v0.31 Major Update](https://store.steampowered.com/news/app/1496640/view/3419948145834477881) :)
