### ISSUE TITLE
[Bug]: (gameplay) crucible now ignores the furnace temperature

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#72]
### Describe the bug

the crucible ignores the furnace's temperature, increasing until the cap despite that it should stay with the furnace's temperature as a soft cap.

This isn't realistic, thermal dynamics denies that an object can get hotter than whatever is heating it, unless of course there is a chemical reaction such as violent oxidization or fire (still oxidization, carbon structures turn to carbon dioxide/monoxide) that heat causes to the object that it is applied to, this may allow iron specifically to get hotter at a specific heat point for a while as it rapidly oxidizes into iron oxide (rust), but this shouldn't happen with any other materials no matter how hard you try.

Considering that the furnace temperature would refer to the average temperature of the air in the furnace, the metal should heat to around that point before drastically slowing down, as soon as it hits this average it will hover around this point with minor fluctuations here and there to reference different air particles hitting it, but of course this is all too complex for such a simplistic game, and a simple soft cap would do.

### Screenshot(s)/Video(s)

https://user-images.githubusercontent.com/101810723/189550933-fbbb8f29-3801-4e43-9a6a-222bc2b79b49.mp4

**Comment by FuryFight3r** [comment]
Hi there Aus, thank you for reporting this, this is most certainly not intended but I will look into this and see what may be the cause of the issue. I am guessing it has something to do with the new code added to fix the resetting temp issue, the code should now start lowering the temp if the crucible is greater than the furnace temp, or the furnace is off, or the crucible is not attached to the furnace, but by the looks of it, it seems to be ignoring the 'if greater than the furnace temp' part of the script. I will try have a HotFix out for this tonight 🙂

**Comment by FuryFight3r** [comment]
Hi again @aus2004 

The latest update [v0.30.8](https://steamcommunity.com/games/1496640/announcements/detail/3302850737224474511) should fix this bug.

Thanks again for reporting this 🙂
