### ISSUE TITLE
[Bug]: (gameplay) crucible bugbox is slightly too big

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#73]
### Describe the bug

The bug box for the crucible extends out of the actual spot where things can get stuck on both sides, making it possible to send both yourself and items to the bug box accidentally

### Screenshot(s)/Video(s)

https://user-images.githubusercontent.com/101810723/189560913-1c1380da-edbd-46dd-9b67-bee6307b3ed6.mp4

sorry about the bad quality, somehow this video is bigger than my other longer videos for no reason

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this 🙂
If only I had of crouched during my testing I may have come across this 😅😅
I will have this fixed in the next HotFix that should be released later tonight

**Comment by FuryFight3r** [comment]
Hi again @aus2004 

The latest update [v0.30.8](https://steamcommunity.com/games/1496640/announcements/detail/3302850737224474511) should fix this bug.

Thanks again for reporting this 🙂
