### ISSUE TITLE
[Bug]: <Ingot Mould stealing>

### ISSUE THREAD

**Issue by Etoilevent** [FuryFight3r/ScrappingSimulator#78]
### Describe the bug

Hi it's me again, so after buying my furnace and crucible, i've wanted to buy the mould. 
But the mould what to mush for my little scrapper budget, then i just clicked on them and taked them xD.

more seriously, you don't need to have the money for buying mould. message saying you don't have the money appears, but the mould is taken and the cashier don't react.

### Reproduction Steps

1 : click on the ingot mould without having enought money (after having buyed the furnace because you can't buy the mould without the furnace)
2 : you have now 0 money but you have the mould, and you can now buy the other 3 for free.

### Expected behaviour

can't buy if i don't have the money to buy. 
(or maybe the cashier come and punch me for stealing is stuff).

### Console output

by the way, i noticed that the price of the ingot mould go down after each purchase. don't know if it was intended.
I took the opportunity to check all the items, the ingot mould it the only one to have it. (buying without money)

![2022-09-25 13_04_10-Scrapping Simulator](https://user-images.githubusercontent.com/49607897/192140337-bd18a5b4-dfed-4ca0-a052-1ec57d4ed413.png)

**Comment by FuryFight3r** [comment]
Hi there @Etoilevent,
Thank you for reporting this, I will look into this to see what could be causing the issue :)

**Comment by FuryFight3r** [comment]
Hi again, @Etoilevent.
Thanks again for reporting this, It has now been patched in the [v0.31 Major Update](https://store.steampowered.com/news/app/1496640/view/3419948145834477881) :)
