### ISSUE TITLE
[Suggestion]: Rotating Objects

### ISSUE THREAD

**Issue by SpercWolf** [FuryFight3r/ScrappingSimulator#79]
### What is your Suggestion?

Please forgive if this is already possible in the game and I just maybe haven't figured out how to yet but I constantly run into the issue of the wooden ingot carrying crate to flip onto its top. I see that I can rotate it clock/counter clock wise with the wheel on my mouse but I do not see a way to spin/rotate it the other direction causing me to have to try and drop it on the corner of a desk or other item to get it to flip back upright as it lands on the ground.

### How will this suggestion fit into the Scope of Scrapping Simulator?

It will make the game easier to control.

### How would the Game and Community benefit from this suggestion?

Obviously make it easier to handle mats.

**Comment by FuryFight3r** [comment]
Hi there SpercWolf,

I hope you are doing well 🙂 there is a few ways to get around this, you can use the Mouse Wheel for normal rotation, with the addition of Holding [Left CTRL] or [Left ALT] to rotate the object in different axis.
Alternatively you can press [R] to quickly reset the carried Objects Rotation back to default.
Hopefully this helps 🙂👍

**Comment by SpercWolf** [comment]
Thank u

**Comment by FuryFight3r** [comment]
Hi there @SpercWolf 

I have since added the UI showing controls for object Rotations and such in the [v0.31.2 Update](https://store.steampowered.com/news/app/1496640/view/3499888838247614196), thanks again for bringing this to my attention 🙂👍
