### ISSUE TITLE
[Bug]: Mine Sweepin UI Stuck

### ISSUE THREAD

**Issue by MrJohnnyB82** [FuryFight3r/ScrappingSimulator#8]
### Describe the bug

When completing a game of MineSweepin.exe the UI buttons for Reset or Exit do not go away after clicking Reset.  New game load behind the UI and can still be played normally.  Exiting the PC and loading Mine Sweepin again does not fix the issue.

### Reproduction Steps

1. Access the PC
2. Open MineSweepin.exe
3. play a game until I click a bomb
4. UI for Reset or Exit comes up
5. click reset to start a new game
6. game loads in the background UI stays up
7. exit MineSweepin and relaunch
8. UI is still there

### Expected behaviour

Expect UI to go away after clicking reset and then reappear after finishing next game.

### Screenshot(s)/Video(s)

![20220123104210_1](https://user-images.githubusercontent.com/47801250/150686651-50ed950f-f256-46b9-8d37-4da7566e0d63.jpg)
![20220123104216_1](https://user-images.githubusercontent.com/47801250/150686654-041c2319-9e68-4435-96e7-cdd267162bc6.jpg)

### Console output

No messages appear in console.  Save game and rechecked console:
13 Objects were Sucessfully Saved
Trollie Position Saved
1 Active Deliveries were Sucessfully Saved
Saved 'Stats' Script Values
Sucessfully Saved - No Errors Present

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920777/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920778/Player-prev.log)

**Comment by FuryFight3r** [comment]
Thank you for this report, I will look into this asap :)

**Comment by FuryFight3r** [comment]
Thanks again for the report - This has now been patched in v0.28.4 :)
