### ISSUE TITLE
[Bug]: <Stuck in sleep loop>

### ISSUE THREAD

**Issue by DragonRapide** [FuryFight3r/ScrappingSimulator#81]
### Describe the bug

Started a new game, went through tutorial. Energy was low, went to bed to sleep. In game time did not pass, just stayed at 7. When I woke up time was 1900, no energy was regained and character passed out. Then character woke up and had gained no energy, so they passed out again. This continued in a loop. Only error shown was:

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <d4cde64232cf45659d86aafa597faa77>:0)
DistantLands.Cozy.CozyEcosystem.WeightedRandom (DistantLands.Cozy.Data.WeatherProfile[] profiles) (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.ForecastNewWeather () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.SetupWeather () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.Awake () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyWeather.Awake () (at <70bdaeb405004c69ae52c67fe037d085>:0)

### Console output

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <d4cde64232cf45659d86aafa597faa77>:0)
DistantLands.Cozy.CozyEcosystem.WeightedRandom (DistantLands.Cozy.Data.WeatherProfile[] profiles) (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.ForecastNewWeather () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.SetupWeather () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyEcosystem.Awake () (at <70bdaeb405004c69ae52c67fe037d085>:0)
DistantLands.Cozy.CozyWeather.Awake () (at <70bdaeb405004c69ae52c67fe037d085>:0)

**Comment by FuryFight3r** [comment]
Hi there @DragonRapide
I apologise about this, I will have a HotFix out asap 👍

**Comment by FuryFight3r** [comment]
Hi there @DragonRapide 
Thanks again for reporting this, I have just upload a HotFix that should fix Time being frozen - which also caused a few other issues like no energy regain, shops wouldn't open etc 🙂👍
