### ISSUE TITLE
[Bug]:shops not always open when they should be

### ISSUE THREAD

**Issue by JClaunch** [FuryFight3r/ScrappingSimulator#82]
### Describe the bug

I've noticed particularly with the Hardware store, sometimes it's not open during business hours.  Saving and reloading the game fix the issue so I assume it's some sort of flagging issue.

### Expected behaviour

Store to be open during business hours.

**Comment by FuryFight3r** [comment]
Hi there @JClaunch 
Thank you for reporting this, someone else has also reported this so it may be quite a common issue, I am working late today, but hopefully I can have it patched by tomorrow after work 🙂👍

**Comment by FuryFight3r** [comment]
Hi @JClaunch 
Thanks again for reporting this, I have released a HotFix update that should hopefully prevent this from happening in the future 🙂👍
