### ISSUE TITLE
[Bug]: Crucible Dissapeared, yet game won't let me buy another...

### ISSUE THREAD

**Issue by Timberln59** [FuryFight3r/ScrappingSimulator#84]
### Describe the bug

After smelting some Iron, I filled the mold that sits on the furnace and went to fill a mold that sits on the wooden table that you buy.  I bumped the table with it, there was a boink sound and the cruicible disappeared.  It's not in the Garage, or behind it, etc..  But the Game won't let me buy another one.  How can I fix this?
Where do I find my Player logs so that I can submit them, in case they show what happened?
As for reproducing the error, try what I did.. I don't know if that will reproduce it.  I also tried quitting out of the game completely and going back in, but the Crucible is still gone...

**Comment by Timberln59** [comment]
I "found" the "bug fixes" button and managed to reset the crucible :)  Still don't know WHY it disappeared but at least I've got it back.  Maybe you should Let people buy more than one?

**Comment by FuryFight3r** [comment]
Hi there @Timberln59 thank you for reporting this, I do know the Chemical station is a little buggy at the moment, though I am unsure of what could be causing this, there is nothing coded in for the Gold/Silver Ingot Mould that should interact with the furnace crucible in any way.

The only thing I can think of is it may have collided with the Bug Return Box that is inside the Chemical Station and been transported to the Bug Box in your bedroom, if it does happen again (or any object disappearing randomly for that matter) most time will be transported to the bug box 🙂 if this is the case, I will tweak the Collider inside the Chemical Station so this doesn't happen again 🙂👍

**Comment by Timberln59** [comment]
Greetings,
Thank YOU for making a great game with lots of Potential!  :)  I had a couple of thoughts on the game...  I am older and need glasses.  How about coloring all screws, etc... to Black, or some other easy to see color?  While grey/silver IS what most screws really are, it makes it hard to see them in the background, unless I zoom way in.  Also, the "bug fix" selection is really great, but you should put a msg on the bug posting section - Before posting a bug, Please check the "bug fix" section on the menu.  I would have been waiting to hear from you about the crucible, IF I hadn't chanced upon the "bug fix" button, etc...  I also am wondering, what would happen if I hadn't purchased the furnace, crucible, etc... and pushed the crucible reset button?  Would it have added on in my game?  Just wondering if you'd thought to block stuff like that..
   Anyways,
    Thanks!
      Timby

**Comment by FuryFight3r** [comment]
Hi again @Timberln59


Thank you for your suggestions 🙂 I could certainly see about changing the Screw colour as they have become quite hard to see after this last Visual update, at the moment they are just using the standard 'Iron' colour but I think if I make the screws have their own seperate colour being a little darker would help them stick out a little better.

I soon will be reworking the 'Bug Fixes' menu and removing the Menu based one to replace it with the Commands one, but I could possibly incorporate the Bug Fixing methods into the Tutorial aswell as having a message within GitHub or something that indicates that the Bug Fixes menu should be looked at first before posting a report 🙂

Also yeah, all the Commands/Fixes have a check that verifies if the object is owned or not, if so the fix proceeds, if not, it doesn't go forward with the Command/Fix 👍🙂

**Comment by FuryFight3r** [comment]
Hi there @Timberln59,

Thanks again for your great suggestions, I have since implemented them in the [v0.31.2 Update](https://store.steampowered.com/news/app/1496640/view/3499888838247614196) 👍🙂


Regards,
Fury

**Comment by Timberln59** [comment]
Greetings,
I'm glad to be able to Help!  It's a fun game(at least to ME), and it's got a lot of Potential...  Here's what I've found this time :) - The Microwave has white screws on a white background/paint.  The Server(with 1 Ram chip) won't let me pull the Ram chip.  It says there's a Child object somewhere, but I don't see anything.  How about adding the ability to take a screen shot to show our Problems/Errors so we can send them to you?  Other servers with multiple Ram chips have no problems and I haven't gotten another Server with ONE chip again...  The PSU(Power supply) has screws that are white, on a white background.  You can see them, but not as easy as if they were a diff color...  Lastly, a Suggestion - How about making Objects "Snap to" on the 2 wheeler?  It would make it MUCH easier to load it...  Or give us a "Lil Red Wagon"  Like we had as kids... :)  The Material Storage buckets - Only have Iron and Aluminum so far.  I didn't realize I could smelt Brass and Copper until I noticed it on the Pull down menu on the Crucible.  Maybe add them to the Storage Bucket availability?  I also noticed that one time, when I was using the blow torch to melt the silver Powder, it sat there, flame on, for a few mins with the temp saying Zero Celsius, it didn't update the temp, until I used F to lift up the torch and then put it down again.  Then it registered the correct updated temp.  Dunno if it's a glitch or what.  It didn't do it on previous crucible loads of Silver OR Gold, etc...  I also find it frustrating to be doing something and having the eyes shut because it's almost Nite nite time :)  How about an audio alarm, like a watch beeping to let us know that it's almost bed time?  It's frustrating to try and run in the house with the eyes shutting ...  :P


   Keep up the Great Work!
    Thanks,
      Timby
a.k.a. Timberln on Steam

**Comment by Timberln59** [comment]
Greetings again,
 I forgot something I'd wanted to request if it's not TOO difficult... I play the Steam game Tank Mechanic Simulator, and I've helped the dev's with errors just like I'm doing with you.  I noticed that in the Tank recovery missions, which are out in the wilderness that they created a wonderful randomized bird calls and wind noises.  It's SO realistic, that you don't even notice it after a couple of minutes.  Your Brain just automatically sorts it as normal background sounds and you start to blank it out.  It's so nice and relaxing too...  
  When I played your game tonight, it seemed to Rain and thunder a lot.  Coincidentally it was Rainy and windy here in New England/Massachusetts tonight too :)  If you could implement a more realistic background sound scheme, it would help players to relax while playing and I think they'd have better enjoyment during their Game session.
   Just a thought.. :)
     Thanks,
       Timby

**Comment by FuryFight3r** [comment]
Hi there @Timberln59 

Thank you for your suggestions 🙂

I may need to create another entire seperate screw and color to go onto objects such as the Microwave and PSU and such that could be more dark rather than light to help solve that issue.

With the server and RAM issue another player has brought this up also, I am currently diagnosing this issue, if you wanted to just get rid of the bugged Servers you can sell them to the pawn shop 🙂

I hadn't even considered adding a screenshot function to the game as Steam itself does a pretty good job of this by taking a screenshot and generating a share link (if you choose to), where as if I were to implement such a system, it could take a screenshot, but then the player would have to go digging through folders to find the screenshot save location and then manually upload the screenshot, you could also use the PrntScrn button on your keyboard to take a Screen Capture (which will be copied to your computer's clipboard) which you can then paste into Paint.exe for example and save the file 🙂👍

There is plans to add a bigger version of the Trolley which would somewhat resemble the Old school wagons and also a smaller version like the Ingot Carry Box but for Parts like RAM, HDDs etc, though I have tried to steer clear of snapping points as it either requires a lot of math in code (which I am not the greatest at) to calculate positions, or creating multiple preset locations, which wouldn't bode well with objects of varying sizes, I feel the way the Trolley interacts with objects at the moment is the most efficient and dynamic way (code wise) as any object that can be picked up can be attached to it, including any future items brought into the game without any extra lines of code, I am however attempting to rework the way the Trolley handles while moving it so it won't look so riding 🙂👍

I am not too sure what you mean with the storage buckets, they should be able to hold every material, unless something has gone awry with the Interface you should just be able to click the dropdown and be presented with all 7 materials currently in the game for you to select, I will have a look into this and see if I can replicate it 👍🙂

There is certainly many issues with the Chemical Station at the moment, it's heading toward a full rework in the very near future 😅 the issue here is that the temperature function doesn't initiate until it receives a signal that the Blow Torch has been lowered onto the Crucible, so if the torch is already pitched toward the Crucible when the Silver/Gold Powder is added it never receives the signal that the Blow Torch is in position thus not starting the Temperature raise process.

I also felt a little the same with the eye shutting mechanic, it does feel a little disorienting especially while moving, I could possibly add a Watch beeping SFX rather than the standard Error Buzz to the Sleepy and Tired Notifications, aswell as making the Eye shutting mechanic quicker, possibly somewhat transparent and or even make it so it only partially closes rather than fully closes 🙂👍

Thank you for your great Suggestions 👍👍
Regards, 
Fury

**Comment by Timberln59** [comment]
Greetings,
I'll check again with the white storage buckets, but I think on mine it only shows Iron and Aluminum on the drop down menu...  Another thing I forgot to ask about, is owning multiple Ingot Crates.  I'd like to be able to have a crate for each ore, that way, I can just keep it in the garage until it's full.  Like say, one for Gold, silver, and another for each of the other ores.  That way, I can wait until the crate is full before I bring it to the Salvage yard.  Right now, I can mix the bars in the box, but if I wanted to bring a box of gold, I'd have to tie up the box and not be able to use it for anything else.  Unless I use the bar shelf.. "which I just got :) "...
  Thanks again!
     Timby

**Comment by FuryFight3r** [comment]
Hi there @Timberln59 

The white Buckets in the game are for Chemical Waste for the Chemical Station, the dark grey ones are the Material Storage Buckets, there could be something going on with the buckets, I will look into the buckets and see what is going on with them 🙂

I am planning to rework both the Ingot Storage Rack and Carry Box mechanics to be easily duplicatable as at the moment they are quite rough, but once the new mechanic is implemented the. I could certainly see about adding extra Crates and Racks 👍🙂

Regards,
Fury

**Comment by FuryFight3r** [comment]
> 
> 
>   Greetings again,
>  I forgot something I'd wanted to request if it's not TOO difficult... I play the Steam game Tank Mechanic Simulator, and I've helped the dev's with errors just like I'm doing with you.  I noticed that in the Tank recovery missions, which are out in the wilderness that they created a wonderful randomized bird calls and wind noises.  It's SO realistic, that you don't even notice it after a couple of minutes.  Your Brain just automatically sorts it as normal background sounds and you start to blank it out.  It's so nice and relaxing too...  
>   When I played your game tonight, it seemed to Rain and thunder a lot.  Coincidentally it was Rainy and windy here in New England/Massachusetts tonight too :)  If you could implement a more realistic background sound scheme, it would help players to relax while playing and I think they'd have better enjoyment during their Game session.
>    Just a thought.. :)
>      Thanks,
>        Timby
> 
> 

Sorry I had missed this message.

I really would like to improve the sounds in-game, unfortunately that is one of the many parts I am not the greatest at when it comes to game Dev 😅 So creating soothing and realistic sounds myself wouldn't be the greatest outcome at the moment 😅, I did somewhat "create" the 'D3ad-Man' vehicle sound effects, by heavily chopping a handful of 2JZ revving and dose sound effects, which really helped improve not only my Sound production skill, but Animations and Triggering specific events during certain phases the car is in 🙂 and the new weather system in the game certainly helps out a lot, but I do get where you are coming from, it still feels/sounds a little lifeless but am slowly working toward improving everything incrementally 🙂👍

But hiring a composer to create both Music Tracks and Environmental Ambient SFX would be quite a costly endeavour, however I could certainly see about investing in a few SFX Packs and mix them to make something that would suit the game style for the time being, once the game is fully released to v1.0 and all goes well with that, I could certainly see about hiring a composer to create a soothing and relaxing sound scheme for the game 🙂👍

**Comment by Timberln59** [comment]
Greetings,
I had a Glitch while playing tonight.  I brought the 2 wheeler to the Hardware store, to try and buy/transport 2 bottles of Hydrogen Peroxide at once.  I brought the 2 wheeler in along side the shelf, exited control of the wheeler and bought 1 bottle.  I then tried to place the bottle on the wheeler to the side of the base platform- to make room on the other side for the 2nd bottle.  When it put the bottle on, it made the wheels go into the floor and not be visible.  I also found that I couldn't move the 2 wheeler.  So I removed the bottle and then was able to move the wheeler and the wheels popped up above the floor again.  So I again tried parking the wheeler and placed 1 bottle on without it going subfloor.  I added the 2nd bottle and it would then NOT let me move the wheeler.  It kept giving me the msg that I should stop moving before trying to exit the wheeler.  As it was getting close to 6pm in game, I removed 1 bottle from the wheeler and ran it home.  However, when I got there, it wouldn't let me go onto the sidewalk.  Almost as if I myself was like the 2 wheeler.  Even moving myself backwards wouldn't let me onto the sidewalk.  I placed the bottle I was carrying onto the sidewalk and returned to the store and got the 2 wheeler.   It still wouldn't let me on the sidewalk.  I tried using the reset_carry to no avail.  I saved my game and it was almost sleep time in game.  I quit to menu and reloaded from save and it then let me ON the sidewalk! :)  I went in, slept and then was able to go to the store and get the 2nd bottle I had bought and carry it home.
  I'd like to request, if you're not already planning it, to implement a carry basket, like the small ones that grocery stores have.  Transporting the bottles and boxes of supplies from the Hardware store one at a time is frustrating.  :)

  You've done a fantastic job so far of creating a Fun Game, and I hate to find stuff to cause you Grief, but I know it only helps you improve the game...
     You've got a dedicated Fan Here, I really Enjoy playing the game and often play for hours at a time!  Years ago, when I was in High School, my Best friend and I, after school, would go to the local dumps and bring back Tv's, radio's, etc...(this was in the 70's, so no computers yet in the dumps) and we'd unsolder the components, and store them in boxes by type.  We had planned on using the parts to make stuff of our own, but we never quite got that far... :)  When my Friend entered Syracuse University in NY.  He donated 2 huge boxes of components that we had gathered and sorted.  The College was Elated!  Free Parts! :)  So it all worked out.  He and I had fun disassembling the electronic stuff.  So you can see why Your Game Appeals to me.

   Keep up the Great Work! and I'll keep helping you make the game better by trying to find bugs :)
     Thanks,
       Timby

**Comment by Timberln59** [comment]
Greetings,
Forgot to mention.  It WAS the Grey resource buckets that I mentioned last time, not the White.  When I generally think of a 5 Gallon Pail, I think of a white one, since that's the most common around here.  It appears that the grey buckets COULD have all of the different materials, not JUST Iron and Aluminum and When you made the slider bar easier to see, that "fixed" the issue I had.
  Thanx again! :)
    Timby

**Comment by FuryFight3r** [comment]
Hi there @Timberln59 
Thank you for pointing that out, it may be an issue with the Chemical Bottles them selves not interacting with the Trolley correctly, I will look into this and hopefully resolve it 🙂
