### ISSUE TITLE
The silver powder wont melt with the blow torch

### ISSUE THREAD

**Issue by ScrapperManHeHe** [FuryFight3r/ScrappingSimulator#85]
### Describe the bug

I try to use the blowtorch to melt the silver but the temp wont go up it just stays the same it was. I put it in the crucible and it wont move from 0 degrees

### Expected behaviour

I need the blow torch to start melting the silver powder on the crucible.

### Screenshot(s)/Video(s)

![Scrapping Simulator 11_29_2022 6_31_39 PM](https://user-images.githubusercontent.com/119461751/204672064-c7134b93-efdf-4d11-b0b3-54de1222e3cb.png)
![Scrapping Simulator 11_29_2022 6_57_25 PM](https://user-images.githubusercontent.com/119461751/204674571-f405a410-caea-4025-974d-ae08f51176ca.png)

### Console output

NullReferenceException: Object reference not set to an instance of an object
PCInteract+<addItemCoroutine>d__160.MoveNext () (at <f7c7b202f89846efa80542a20214f6e3>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c6a0be87269c4a56aa4c8bc00101797f>:0)

**Comment by FuryFight3r** [comment]
Hi there @ScrapperManHeHe 

This usually happens when the torch is left in position after finishing the previous Ingot, you should just be able to lift, then lower the Blow Torch again to get the temperature started. The Chemical Station is currently very messy and will be getting a complete overhaul in the very near future 🙂👍

**Comment by ScrapperManHeHe** [comment]
I lighted and lowered but it stayed the same. (sorry for any disruption)

**Comment by FuryFight3r** [comment]
> I lifted and lowered but it stayed the same. (sorry for any disruption)
> just fixed it no more issue

Glad you got it working again, and no need to be sorry, I am here to help 🙂👍
