### ISSUE TITLE
[Bug]: Some parts of an object turn null

### ISSUE THREAD

**Issue by ScrapperManHeHe** [FuryFight3r/ScrappingSimulator#86]
### Describe the bug

when i leave and rejoin, some parts of the object turn purple and look very odd.

### Reproduction Steps

Get an object (such as a microwave)
save your game
leave
join back
then some parts are purple

### Expected behaviour

For the color to be in its usual color

### Screenshot(s)/Video(s)

![Scrapping Simulator 11_29_2022 8_10_11 PM](https://user-images.githubusercontent.com/119461751/204683555-bb213faa-1834-48b8-8984-006ef2aaa724.png)

### Console output

ERROR: Settings was Null, unable to Trigger Mouse Settings in regards to Application Window Mode

**Comment by FuryFight3r** [comment]
Hi there @ScrapperManHeHe 

That is very strange, this use to happen with saved objects after an update, but has been a long while since I've noticed this happen last, I will look into this and hopefully have a patch out asap 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
