### ISSUE TITLE
[Bug]: Server Ram

### ISSUE THREAD

**Issue by CrazyJamie1** [FuryFight3r/ScrappingSimulator#87]
### Describe the bug

I was disassembling a server, when I noticed I couldn't get the ram off of the motherboard in the server.

### Reproduction Steps

1. Obtain a server
2. Start to disassemble the server
3. Take the cover off
4. Try to remove the ram

### Expected behaviour

Being able to remove the ram

### Screenshot(s)/Video(s)

![Server Ram bug](https://user-images.githubusercontent.com/108179614/205511036-7f0f1f69-a6e6-43a4-a21a-9948ecb0e5b5.JPG)

### Player Logs

[Save stuff.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/10149308/Save.stuff.zip)

**Comment by FuryFight3r** [comment]
Hi there @CrazyJamie1,

This seems to be a common bug at the moment, I've heard saving, exiting and reloading can fix this issue, either way I will look into this and hopefully have it patched asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi again @CrazyJamie1,

Thank you for reporting this, I have now released the [v0.31.3 Update](https://store.steampowered.com/news/app/1496640/view/3618109754353953712) to solve this bug :)
