### ISSUE TITLE
[Bug]: some of the queue FX are offset again

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#88]
### Describe the bug

I think the model update effected the origin of models, and that changed the position of the FX again.

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/206637814-27d352ba-fbc3-40a1-a8de-49b9ba415a2e.png)
![image](https://user-images.githubusercontent.com/101810723/206638074-7c83ab7f-de9a-447c-a8f7-f76d09cbdb01.png)

**Comment by FuryFight3r** [comment]
Hi there @aus2004

Thank you for reporting this, do you happen to know what RAM Module that was doing this? or are all modules doing this no matter the Size/Type?

With the Crystal Oscillators this is normal, well I say 'normal', but it is due to my terrible Modeling skills 😅 I had made the model off-centre in Blender, so I will have to remake the model itself to fix this mishap, but will have this fixed in the near future 🙂👍

**Comment by aus2004** [comment]
i believe all ram modules are doing this, but these are from a server if i'm not mistaken.

**Comment by FuryFight3r** [comment]
Thank you for that, I will look into this as it's definitely should not be happening to RAM Modules, as each Chip is its own object and should each have their own centre point (which is used when calculating the position for the Queue and Error FX) so it's very strange that they have been bunched together somewhat.

 Does it seem like it is just the Queue FX that are ill positioned? Or was the entire clicking/hovering area for the Chips squished aswell?

**Comment by aus2004** [comment]
just the queue FX, they aren't squished together, that's just the sparkle being big, but they are offset below the chips.

**Comment by FuryFight3r** [comment]
Ohh I see, sorry I thought that was 5 or so different sparkles all bunched towards the centre, my bad 😅

But I do see what you mean now by they are pretty much positioned at the bottom of the chip.
On-top of fixing that I will also see about adding to the code that handles the FX to make the size dynamic and suit the size of the object, so they are not so glaring on smaller objects 🙂
Hopefully even build toward dynamic heights and rotations for objects such as the PSU, CD Drive, HDDs etc as the FX are all placed in the direct centre of the object which is obscured by the large object itself making it pointless anyway 😅 

Never the less I will fix the positioning (and possibly size) asap 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @aus2004,
Thanks again for reporting this, this should now be resolved with the v0.32.1 update 🙂👍
