### ISSUE TITLE
[Bug]: Aluminum Stuck Inside/Vanish When Placed on Ingot Shelf

### ISSUE THREAD

**Issue by MrJohnnyB82** [FuryFight3r/ScrappingSimulator#9]
### Describe the bug

When placing an aluminum ingot on the ingot shelf it either vanishes or gets stuck inside of the shelf.  Lose ingot.  Iron ingots work with shelf properly, have not tested others as of yet. Nothing was reported in the console.

### Reproduction Steps

1. bought ingot shelf
2. place aluminum ingot on shelf, it vanished
3. placed 2nd aluminum ingot on shelf it vanished
4. placed iron ingot on shelf it worked, took iron ingot off shelf
5. place aluminum ingot on shelf stuck inside shelf

### Expected behaviour

aluminum ingot appears on shelf until removed

### Screenshot(s)/Video(s)

![20220123112426_1](https://user-images.githubusercontent.com/47801250/150688568-c49006af-96e0-4a3b-89ac-fd2c29d2c017.jpg)

### Console output

none

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920883/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/7920884/Player-prev.log)

**Comment by FuryFight3r** [comment]
Hi Poonfury, thank you for reporting this bug, I think it may be a similar issue to the PC issue. I had re-named the Ingot to an 'Aluminium Ingot' while these old scripts are looking for 'Aluminum Ingot', I will have this fixed next patch, I will also implement a pass_phrase you can enter to temporarily remove the Ingot shelf so you can gather the stuck Ingots

**Comment by Poonfury** [comment]
Yeah, I believe I just found another that is related to the name change.  I cant sell aluminum ingots at the scrap yard. 

Unable to Sell **Aluminium** Ingot (1kg) as it is not recognized as an Ingot

**Comment by FuryFight3r** [comment]
> Yeah, I believe I just found another that is related to the name change.  I cant sell aluminum ingots at the scrap yard. 
> 
> Unable to Sell **Aluminium** Ingot (1kg) as it is not recognized as an Ingot
> 

Ahh yeah that is certainly the problem then, just the name change has confused the scripts looking for Aluminum rather then the new Aluminium

**Comment by FuryFight3r** [comment]
Hi there MrJohnnyB,  you will need to press [Right CTRL] + [F9] to open up the Command Panel, you can then type the 'reset_shelf' command to temporarily remove your shelf to recover the ingots, once the bugged Ingots have been recovered you can either retype the command or go to the Hardware Store and attempt to buy the shelf again so it can be turned back on (you wont need to pay for the shelf again). Thanks again for reporting this :)
