### ISSUE TITLE
[Bug]: The tralley is stuck

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#91]
### Describe the bug

I can not use the tralley, since it is stuck to a shelf in the garage.
I have tried everything to get it get it loose, but without luck.

So, maybe there could be a way to move the table/shelf inside the garage, so this not happen again.

### Screenshot(s)/Video(s)

![ScrapperBug](https://user-images.githubusercontent.com/6820904/215346774-18125133-c314-470f-a204-af996e2f32a6.jpg)

**Comment by FuryFight3r** [comment]
Hi there @senoks,

You should be able to use the 'reset_trolley' command to reset the position of the shelf, or you can also type the 'reset_shelf' command to turn the shelf off/on 👍🙂

**Comment by senoks** [comment]
Thank You, It worked well. I didn't know there was a reset command.

________________________________
Fra: FuryFight3r ***@***.***>
Sendt: søndag 29. januar 2023 19:53
Til: FuryFight3r/ScrappingSimulator ***@***.***>
Kopi: Stig Blackie Enoksen ***@***.***>; Mention ***@***.***>
Emne: Re: [FuryFight3r/ScrappingSimulator] [Bug]: The tralley is stuck (Issue #91)


Hi there @senoks<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsenoks&data=05%7C01%7C%7Ce290b5e858ab4d4e823708db022a1e32%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638106152144388964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x%2Bk7Zu3xhdumMxw0jospj%2BQLhcVVONTDXoeX5CqJCNQ%3D&reserved=0>,

You should be able to use the 'reset_trolley' command to reset the position of the shelf, or you can also type the 'reset_shelf' command to turn the shelf off/on 👍🙂
