### ISSUE TITLE
[Bug]: Can't access disassembly mode after loading save

### ISSUE THREAD

**Issue by Jonna3876** [FuryFight3r/ScrappingSimulator#94]
### Describe the bug

I can no longer access the disassembly screen after returning to my save. I'm unsure of how to correctly reproduce the bug, but to the best of my memory, I'll try to provide a reproduction list.

For some reason, I can't disassemble any E-Waste item anymore. Doesn't matter if it's already been moved or freshly spawned and moved to garage.

Saving the game outside of disassembly mode seems to have worked.

### Reproduction Steps

1. Pick up any E-Waste object and begin disassembly
2. Open pause menu
3. Save and exit game
4. Load saved game
5. No longer able to access disassembly mode.

### Expected behaviour

Expected the disassembly of item to continue as before.

**Comment by FuryFight3r** [comment]
Hi there @Jonna3876 
Thank you for taking the time to create a report, you may be able to use the 'reset_desk' command by pressing [F1] which should reset the desk, which should allow you to continue playing,either way I will look into the cause of this and have a fix out asap 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for reporting this @Jonna3876 - I was only able to replicate this in the v0.31.5 version and was not able to do it within the [v0.32 Major Update](https://steamcommunity.com/games/1496640/announcements/detail/3640634660759680357), so I may have unknowingly fixed it, I did tidy up the ID Based saving and loading so it could well have been a conflicting issue there, never the less thank you for reporting this :)
