### ISSUE TITLE
[Bug]: Material Container stuck in ingot shelf

### ISSUE THREAD

**Issue by Jonna3876** [FuryFight3r/ScrappingSimulator#95]
### Describe the bug

Sort of my own fault for not moving the material container in question out of the garage before buying the ingot shelf.

Can't move the material container due to it being stuck in the ingot shelf and no longer being able to be moved (see attached screenshot)

### Reproduction Steps

1. Buy Material Container
2. Move said container to the left of the garage workbench
3. Buy ingot shelf from Hardware Store 
4. Ingot shelf is placed on top of container, thus leaving it stuck

### Expected behaviour

Maybe a warning that items blocking the ingot shelf has been moved outside of garage.

### Screenshot(s)/Video(s)

![20230225002124_1](https://user-images.githubusercontent.com/48834824/221319980-b962dd24-8e0d-4aca-976b-64adc06afa7a.jpg)

**Comment by FuryFight3r** [comment]
Hi there @Jonna3876, you may be able to use the 'reset_shelf' command (accessed by pressing F1) to temporarily hide, you should then be able to grab the Bucket(s) and then type the command again to re-enable the shelf

**Comment by Jonna3876** [comment]
@FuryFight3r Thanks, I'll give it a try :D

**Comment by FuryFight3r** [comment]
Thanks again for reporting this @Jonna3876 - This has now been fixed and shouldn't be able to happen again in the [v0.32 Major Update](https://steamcommunity.com/games/1496640/announcements/detail/3640634660759680357) 🙂👍
