### ISSUE TITLE
[Bug]: Issues with removing ingots from the new shelf

### ISSUE THREAD

**Issue by Jonna3876** [FuryFight3r/ScrappingSimulator#96]
### Describe the bug

Having some issues regarding the removal of ingots (e.g. when bringing larger amounts back and forth to sell)

It seems I can only withdraw ingots from a shelf if it's recently been interacted with. E.g. if an ingot is placed on the top shelf, only ingots on the top shelf can be removed, and vice versa on the middle and bottom shelves.

Adding onto this, I can only remove the last placed ingot first, e.g. if I wanted to remove a copper ingot placed first on the shelf with 4 other ingots next to it, I have to remove the 4 others before I can remove the copper ingot.

### Reproduction Steps

1. Make ingots
2. Place ingots on each shelf
3. Place ingot on any shelf
4. Try to remove ingots from either of the other shelves

### Expected behaviour

Removing ingots regardless of shelf position or position in the queue.

**Comment by FuryFight3r** [comment]
Hi there @Jonna3876 and thank you for reporting this, I will have the removal issue fixed asap.
Though as for the removal of specific individual Ingots, rather than just removing the last added Ingot would be a bit more of a challenge, nevertheless it could certainly be some to work toward for the future 🙂👍

**Comment by FuryFight3r** [comment]
I have just uploaded a Hotfix for this issue, Thank you again for taking the time to create a report :)

- I have also taken note of the Individual Removal Idea and hopefully can come up with a suitable solution on how to handle this soon 👍 :)
